In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pycountry
import csv
import pycountry_convert as pc 
import sqlalchemy
from sqlalchemy import create_engine
import pymysql
from getpass import getpass

In [2]:
data_0 = pd.read_csv("WEO_Data.csv", sep=',')
data_0

,Country,Subject Descriptor,2015,2016,2017,2018,2019,2020,Estimates Start After
0,Albania,"Gross domestic product, constant prices",2.219,3.315,3.802,4.019,2.088,-3.482,2020
1,Albania,"Gross domestic product, current prices",11.389,11.862,13.053,15.157,15.399,15.161,2020
2,Albania,"Gross domestic product, deflator",194.969,193.736,196.547,199.442,201.949,203.32,2020
3,Albania,"Gross domestic product per capita, constant pr...","12,173.62","12,597.30","13,039.70","13,570.55","13,862.63","13,394.46",2020
4,Albania,Total investment,26.237,25.47,24.672,24.118,23.032,22.79,2020
...,...,...,...,...,...,...,...,...,...
1451,Vietnam,General government revenue,19.19,19.067,19.565,19.547,19.648,18.535,2020
1452,Vietnam,General government total expenditure,24.174,22.231,21.529,20.573,20.05,22.444,2020
1453,Vietnam,General government net lending/borrowing,-4.983,-3.164,-1.964,-1.026,-0.402,-3.909,2020
1454,Vietnam,General government gross debt,46.116,47.548,46.32,43.712,41.292,41.668,2020
1455,Vietnam,Current account balance,-0.861,0.248,-0.596,1.903,3.711,4.391,2020

# INFO TABLE

In [3]:
info= pd.read_csv("WEO_info.csv", sep=',')
info

,"Gross domestic product, constant prices",Percent change,Unnamed: 2,"See notes for: Gross domestic product, constant prices (National currency)."
0,"Gross domestic product, current prices",U.S. dollars,Billions,"See notes for: Gross domestic product, curren..."
1,"Gross domestic product, deflator",Index,NaN,"See notes for: Gross domestic product, consta..."
2,"Gross domestic product per capita, constant pr...",Purchasing power parity; 2017 international do...,Units,"See notes for: Gross domestic product, consta..."
3,Total investment,Percent of GDP,NaN,Source: IMF Staff Estimates. Official national...
4,Gross national savings,Percent of GDP,NaN,Source: IMF Staff Estimates. Official national...
5,"Inflation, average consumer prices",Index,NaN,Source: National Statistics Office Latest actu...
6,Volume of imports of goods and services,Percent change,NaN,Source: Central Bank Latest actual data: 2020 ...
7,Volume of exports of goods and services,Percent change,NaN,Source: Central Bank Latest actual data: 2020 ...
8,Unemployment rate,Percent of total labor force,NaN,Source: National Statistics Office Latest actu...
9,Population,Persons,Millions,Source: National Statistics Office. INSTAT Lat...
10,General government revenue,Percent of GDP,NaN,See notes for: General government revenue (Na...
11,General government total expenditure,Percent of GDP,NaN,See notes for: General government total expen...
12,General government net lending/borrowing,Percent of GDP,NaN,See notes for: General government net lending...
13,General government gross debt,Percent of GDP,NaN,See notes for: General government gross debt ...
14,Current account balance,Percent of GDP,NaN,"See notes for: Gross domestic product, curren..."

In [4]:
cols = []
for i in range(len(data_0.columns)):
    cols.append(data_0.columns[i].lower().replace(' ', '_'))
data_0.columns = cols
data_0.head(15)

,country,subject_descriptor,2015,2016,2017,2018,2019,2020,estimates_start_after
0,Albania,"Gross domestic product, constant prices",2.219,3.315,3.802,4.019,2.088,-3.482,2020
1,Albania,"Gross domestic product, current prices",11.389,11.862,13.053,15.157,15.399,15.161,2020
2,Albania,"Gross domestic product, deflator",194.969,193.736,196.547,199.442,201.949,203.32,2020
3,Albania,"Gross domestic product per capita, constant pr...","12,173.62","12,597.30","13,039.70","13,570.55","13,862.63","13,394.46",2020
4,Albania,Total investment,26.237,25.47,24.672,24.118,23.032,22.79,2020
5,Albania,Gross national savings,15.804,16.796,17.085,17.109,14.742,14.074,2020
6,Albania,"Inflation, average consumer prices",100,101.287,103.297,105.393,106.88,108.613,2020
7,Albania,Volume of imports of goods and services,0.076,8.3,5.993,5.765,4.716,-19.517,2020
8,Albania,Volume of exports of goods and services,5.272,10.396,10.1,3.469,1.695,-27.509,2020
9,Albania,Unemployment rate,17.1,15.2,13.7,12.3,11.47,11.675,2020
10,Albania,Population,2.881,2.876,2.884,2.883,2.881,2.878,2020
11,Albania,General government revenue,26.44,27.642,27.756,27.485,27.209,25.905,2020
12,Albania,General government total expenditure,30.758,29.139,29.372,28.802,29.153,32.619,2020
13,Albania,General government net lending/borrowing,-4.318,-1.498,-1.616,-1.317,-1.944,-6.713,2020
14,Albania,General government gross debt,73.716,73.324,71.895,69.466,67.285,75.927,2020

In [5]:
data_15 = data_0[['country', 'subject_descriptor', '2015']]
data_16 = data_0[['country', 'subject_descriptor', '2016']]
data_17 = data_0[['country', 'subject_descriptor', '2017']]
data_18 = data_0[['country', 'subject_descriptor', '2018']]
data_19 = data_0[['country', 'subject_descriptor', '2019']]
data_20 = data_0[['country', 'subject_descriptor', '2020']]
data_15.head(16)

    country                                 subject_descriptor       2015
0   Albania            Gross domestic product, constant prices      2.219
1   Albania             Gross domestic product, current prices     11.389
2   Albania                   Gross domestic product, deflator    194.969
3   Albania  Gross domestic product per capita, constant pr...  12,173.62
4   Albania                                   Total investment     26.237
5   Albania                             Gross national savings     15.804
6   Albania                 Inflation, average consumer prices        100
7   Albania            Volume of imports of goods and services      0.076
8   Albania            Volume of exports of goods and services      5.272
9   Albania                                  Unemployment rate       17.1
10  Albania                                         Population      2.881
11  Albania                         General government revenue      26.44
12  Albania               General government total expenditure     30.758
13  Albania           General government net lending/borrowing     -4.318
14  Albania                      General government gross debt     73.716
15  Albania                            Current account balance     -8.609

# FROM HERE ALL TRANSFORMATIONS ARE  INCLUDED IN CLEANING FUNCTIONS AT THE END

In [ ]:
def pivot_and_column_names(df):
        df= df.pivot(index='country', columns=df[['subject_descriptor']])
        #rename columns:
        df.columns = ['acc_bal','gross_debt','gov_net_len/borr','gov_rev','gov_expend','gdp_percap_cons','gdp_cons',
                      'gdp_curr', 'gdp_defl', 'gross_savings','inflation_ind','pop','tot_invest', 'unemployment', 
                      'export_g_s', 'import_g_s']
        #arrange order:
        df = df[['acc_bal','gov_rev','gov_expend','gdp_percap_cons','inflation_ind','gov_net_len/borr','tot_invest',
                    'gross_savings','pop', 'unemployment', 
                    'export_g_s', 'import_g_s','gdp_defl','gross_debt','gdp_cons','gdp_curr']]
        return df
pivot_and_column_names(data_20)

In [ ]:
d_15 = column_names(data_15)
d_16 = column_names(data_16)
d_17 = column_names(data_17)
d_18 = column_names(data_18)
d_19 = column_names(data_19)
d_20 = column_names(data_20)
d_15

In [ ]:
#I see the column 'gdp_percap_cons' has commas to separate the 1000s 
#as per error: 'could not convert string to float: '12,173.62''

# https://www.adamsmith.haus/python/answers/how-to-remove-a-comma-from-a-string-in-python

def clean_comma(df):
    for i in df.columns:
        df[i] = df[i].str.replace(',', '')
    return df 
clean_comma(d_15)
clean_comma(d_16)
clean_comma(d_17)
clean_comma(d_18)
clean_comma(d_19)
clean_comma(d_20)

#I will include it in the cleaning function

In [ ]:
#transform dtypes to numerics 
def to_num(df):
    df = df.astype(np.number)
    print(df.dtypes)

to_num(d_15)
to_num(d_16)
to_num(d_17)
to_num(d_18)
to_num(d_19)
to_num(d_20)
display(d_20)

In [ ]:
d_15.to_csv('d_15.csv', index=True)
d_16.to_csv('d_16.csv', index=True)
d_17.to_csv('d_17.csv', index=True)
d_18.to_csv('d_18.csv', index=True)
d_19.to_csv('d_19.csv', index=True)
d_20.to_csv('d_20.csv', index=True)

In [ ]:
d15 = pd.read_csv("d_15.csv")
d16 = pd.read_csv("d_16.csv")
d17 = pd.read_csv("d_17.csv")
d18 = pd.read_csv("d_18.csv")
d19 = pd.read_csv("d_19.csv")
d20 = pd.read_csv("d_20.csv")
d15

In [ ]:
d15.isnull().sum()

In [ ]:
d15.dtypes

Add 2 categorical columns by region and by economy size

Region / Continent :

I found this library "pycountry" :

Which through the country code, gives the continent. 
import pycountry_convert as pc

country_code = pc.country_name_to_country_alpha2("China", cn_name_format="default")
print(country_code)
continent_name = pc.country_alpha2_to_continent_code(country_code)
print(continent_name)
I am going to create a colulmn called "region"

In [ ]:
#clean and convert not ISO recognised country names 
#list of correct contry names (ISO) found here: 
#https://stackoverflow.com/questions/16253060/how-to-convert-country-names-to-iso-3166-1-alpha-2-values-using-python
# 'Kosovo' is not a recognsed country by ISO 3166 so I am going to name it Serbia (keeps the index order) just to get the country code

def replace_wrong_names(df):
    df[['country']] = df[['country']].replace(['Hong Kong SAR',"Korea",'Kosovo', 'Taiwan Province of China', 'The Bahamas' ], ['Hong Kong', 'Korea, Republic of', 'Montenegro','Taiwan, Province of China',  'Bahamas'])
    
# replace_wrong_names(d15)
# replace_wrong_names(d16)
# replace_wrong_names(d17)
# replace_wrong_names(d18)
# replace_wrong_names(d19)
# replace_wrong_names(d20)

In [ ]:
def code_co(df):
    df['code'] = df['country'].apply(pc.country_name_to_country_alpha2)
   

code_co(d15)
code_co(d16)
code_co(d17)
code_co(d18)
code_co(d19)
code_co(d20)




# d15['code'] = d15['country'].apply(pc.country_name_to_country_alpha2)
# d15['code']

In [ ]:
def create_cont(df):
    df['continent'] = df['code'].apply(pc.country_alpha2_to_continent_code)
    df.drop('code', axis=1, inplace=True)
    #rename Kosovo back
    df['country'][43]= 'Kosovo'


create_cont(d15)
create_cont(d16)
create_cont(d17)
create_cont(d18)
create_cont(d19)
create_cont(d20)

# d15['continent'] = d15['code'].apply(pc.country_alpha2_to_continent_code)
# d15['continent'] 
# continents = {
#     'NA': 'North America',
#     'SA': 'South America', 
#     'AS': 'Asia',
#     'OC': 'Australia',
#     'AF': 'Africa',
#     'EU': 'Europe'
# }

In [ ]:
d15

Economy size: 



% GDP growth Vs LY 
Unemployment
Population

In [ ]:
#add a new column with a classification (Total expenditure)

In [ ]:
# % of GDP
def spend_class(df):
#   df['spend_class'] = df["gov_expend"].copy()
    labels = ["S1", "S2", "S3","S4"]
    df['spend_class'] = pd.qcut(df["gov_expend"],4, labels = labels)
    
    
spend_class(d20)

In [ ]:
["gov_expend"].isna().sum()

In [ ]:
d15['gross_debt'].describe()

In [ ]:
def gross_debt_class(df):
    labels = ["0%-5%", "5%-20%", "20%-40%", "40%-60%", "Very High"]
    df['debt_class'] = pd.cut(df['gross_debt'],[0,5,20,40,60,228.397000], labels = labels)
    
gross_debt_class(d20)

In [ ]:
d15['tot_invest'].describe()

In [ ]:
def invest_class(df):
    labels = ["0%-20%", "20%-30%", "30%-40%", ">40"]
    df['invest/gdp_class'] = pd.cut(df['tot_invest'],[12,20,30,40,51], labels = labels)
   
invest_class(d20)

In [ ]:
def order_columns(df):
    df= df[['country','continent','acc_bal','gdp_defl','inflation_ind','gob rev','gov_expend','gob_net_len/borr','tot_invest',
                'gross_savings', 'export_g_s', 'import_g_s','gross_debt','pop', 'unemployment','gdp_percap_cons','gdp_cons','gdp_curr']]

In [6]:
def data_grooming(df):
    df = df.pivot(index='country', columns=df[['subject_descriptor']])
    #rename columns:
    df.columns = ['acc_bal','gross_debt','gov_net_len/borr','gov_rev','gov_expend','gdp_percap_cons','gdp_cons',
                    'gdp_curr', 'gdp_defl', 'gross_savings','inflation_ind','pop','tot_invest', 'unemployment', 
                    'export_g_s', 'import_g_s']
    #arrange order:
    df = df[['acc_bal','gov_rev','gov_expend','gdp_percap_cons','inflation_ind','gov_net_len/borr','tot_invest',
                    'gross_savings','pop', 'unemployment', 
                    'export_g_s', 'import_g_s','gdp_defl','gross_debt','gdp_cons','gdp_curr']]
    #clean commas in 1000s values:
    for i in df.columns:
        df[i] = df[i].str.replace(',', '')
    #transform dtypes to numerics 
    df = df.astype(np.number)
    return df
    
    
def data_cleaning(df):
    df['country'] = df['country'].replace(['Hong Kong SAR',"Korea",'Kosovo','Taiwan Province of China','The Bahamas'], ['Hong Kong','Korea, Republic of','Montenegro','Taiwan, Province of China','Bahamas'])
    df['code'] = df['country'].apply(pc.country_name_to_country_alpha2)
    df['continent'] = df['code'].apply(pc.country_alpha2_to_continent_code)
    df.drop('code', axis=1, inplace=True)
    #rename Kosovo back
    df['country'].replace('Montenegro', 'Kosovo')
    display(df)
    #Spend_class
    #df['spend_class'] = df["gov_expend"].copy()
    labels = ["S1", "S2", "S3","S4"]
    df['spend_class'] = pd.qcut(df["gov_expend"],4, labels = labels)
    display(df)
    #gross_debt_class
    #df['debt_class'] = df["gross_debt"].copy()
    labels = ["0%-5%", "5%-20%", "20%-40%", "40%-60%", "Very High"]
    df['debt_class'] = pd.cut(df['gross_debt'],[0,5,20,40,60,228.397000], labels = labels)
    display(df)
    #invest_class(df):
    #df['invest/gdp_class'] = df["tot_invest"].copy()
    labels = ["0%-20%", "20%-30%", "30%-40%", ">40"]
    df['invest/gdp_class'] = pd.cut(df['tot_invest'],[12,20,30,40,51], labels = labels)
    display(df)
    #reorder columns :
    df = df[['country','continent','spend_class','debt_class','invest/gdp_class','acc_bal','gdp_defl','inflation_ind','gov_rev','gov_expend','gov_net_len/borr','tot_invest','gross_savings', 'export_g_s', 'import_g_s','gross_debt','pop', 'unemployment','gdp_percap_cons','gdp_cons','gdp_curr']]
    display(df)

In [7]:
d_15_g = data_grooming(data_15)
d_16_g = data_grooming(data_16)
d_17_g = data_grooming(data_17)
d_18_g = data_grooming(data_18)
d_19_g = data_grooming(data_19)
d_20_g = data_grooming(data_20)

In [8]:
d_20_g

,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr
country,,,,,,,,,,,,,,,,
Albania,-8.677,25.905,32.619,13394.46,108.613,-6.713,22.790,14.074,2.878,11.675,-27.509,-19.517,203.320,75.927,-3.482,15.161
Algeria,-12.677,30.128,36.868,10747.35,211.180,-6.740,42.597,29.921,43.851,14.652,-4.154,-18.914,261.583,51.324,-4.900,147.600
Argentina,0.852,33.466,42.092,19685.74,619.207,-8.626,17.913,18.765,45.388,11.550,-13.124,-10.722,4400.780,102.790,-9.895,389.064
Armenia,-3.787,25.247,30.649,12631.53,218.396,-5.403,18.532,14.746,2.962,18.100,-35.571,-30.991,162.702,63.476,-7.395,12.641
Australia,2.595,36.090,44.674,49088.42,116.175,-8.585,22.271,24.870,25.684,6.492,-9.822,-13.014,100.348,57.828,-2.179,1357.320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
United Kingdom,-2.502,36.160,48.921,42975.53,108.736,-12.761,16.693,14.192,67.081,4.525,-12.961,-15.769,105.091,102.608,-9.270,2758.870
United States,-2.949,30.804,45.296,59803.38,258.838,-14.492,21.152,19.158,331.234,8.092,-13.561,-8.933,113.647,134.238,-3.405,20893.750
Uruguay,-0.839,28.124,32.793,21200.62,216.725,-4.668,17.423,16.585,3.531,10.350,-19.065,-12.710,135.485,68.143,-6.115,53.561
Uzbekistan,-5.021,26.356,28.873,7415.02,313.051,-2.517,38.674,33.652,33.905,10.531,-20.029,-12.844,100.000,37.601,1.886,59.893
Vietnam,4.391,18.535,22.444,10331.25,282.118,-3.909,32.110,36.485,97.406,3.300,3.569,2.655,159.726,41.668,2.944,342.941

In [9]:
d_15_g.to_csv('d_15_g.csv', index=True)
d_16_g.to_csv('d_16_g.csv', index=True)
d_17_g.to_csv('d_17_g.csv', index=True)
d_18_g.to_csv('d_18_g.csv', index=True)
d_19_g.to_csv('d_19_g.csv', index=True)
d_20_g.to_csv('d_20_g.csv', index=True)

In [10]:
dd15 = pd.read_csv("d_15_g.csv")
dd16 = pd.read_csv("d_16_g.csv")
dd17 = pd.read_csv("d_17_g.csv")
dd18 = pd.read_csv("d_18_g.csv")
dd19 = pd.read_csv("d_19_g.csv")
dd20 = pd.read_csv("d_20_g.csv")

In [11]:
dd20

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr
0,Albania,-8.677,25.905,32.619,13394.46,108.613,-6.713,22.790,14.074,2.878,11.675,-27.509,-19.517,203.320,75.927,-3.482,15.161
1,Algeria,-12.677,30.128,36.868,10747.35,211.180,-6.740,42.597,29.921,43.851,14.652,-4.154,-18.914,261.583,51.324,-4.900,147.600
2,Argentina,0.852,33.466,42.092,19685.74,619.207,-8.626,17.913,18.765,45.388,11.550,-13.124,-10.722,4400.780,102.790,-9.895,389.064
3,Armenia,-3.787,25.247,30.649,12631.53,218.396,-5.403,18.532,14.746,2.962,18.100,-35.571,-30.991,162.702,63.476,-7.395,12.641
4,Australia,2.595,36.090,44.674,49088.42,116.175,-8.585,22.271,24.870,25.684,6.492,-9.822,-13.014,100.348,57.828,-2.179,1357.320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-2.502,36.160,48.921,42975.53,108.736,-12.761,16.693,14.192,67.081,4.525,-12.961,-15.769,105.091,102.608,-9.270,2758.870
87,United States,-2.949,30.804,45.296,59803.38,258.838,-14.492,21.152,19.158,331.234,8.092,-13.561,-8.933,113.647,134.238,-3.405,20893.750
88,Uruguay,-0.839,28.124,32.793,21200.62,216.725,-4.668,17.423,16.585,3.531,10.350,-19.065,-12.710,135.485,68.143,-6.115,53.561
89,Uzbekistan,-5.021,26.356,28.873,7415.02,313.051,-2.517,38.674,33.652,33.905,10.531,-20.029,-12.844,100.000,37.601,1.886,59.893
90,Vietnam,4.391,18.535,22.444,10331.25,282.118,-3.909,32.110,36.485,97.406,3.300,3.569,2.655,159.726,41.668,2.944,342.941

In [12]:
data_cleaning(dd15)
data_cleaning(dd16)
data_cleaning(dd17)
data_cleaning(dd18)
data_cleaning(dd19)
data_cleaning(dd20)

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent
0,Albania,-8.609,26.440,30.758,12173.62,100.000,-4.318,26.237,15.804,2.881,17.100,5.272,0.076,194.969,73.716,2.219,11.389,EU
1,Algeria,-16.442,30.544,45.811,11616.72,172.653,-15.267,50.781,34.326,39.963,11.214,5.733,-6.048,237.033,8.733,3.700,165.979,AF
2,Argentina,-2.743,35.366,41.366,23933.89,168.000,-6.001,17.071,14.328,43.132,6.533,-1.633,2.644,825.311,52.563,2.731,642.464,SA
3,Armenia,-2.685,21.494,26.331,11074.41,208.046,-4.837,21.204,18.519,2.990,18.500,9.679,-9.819,149.985,44.133,3.254,10.553,AS
4,Australia,-4.637,34.599,37.387,48757.65,107.650,-2.788,25.910,21.652,23.985,6.058,6.319,2.259,90.165,37.751,2.310,1233.140,OC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-5.165,35.486,39.993,45208.37,100.000,-4.507,17.646,12.481,65.110,5.375,3.765,4.994,92.626,86.022,2.623,2957.230,EU
87,United States,-2.246,31.673,35.205,58385.72,237.002,-3.532,21.201,20.156,320.926,5.275,0.271,5.187,104.691,105.142,2.707,18206.030,NA
88,Uruguay,-0.254,26.607,28.472,22069.82,146.058,-1.865,19.469,19.215,3.467,7.525,-7.755,-8.122,93.157,58.152,0.371,57.874,SA
89,Uzbekistan,1.046,24.325,24.567,6458.15,166.288,-0.242,24.698,25.744,31.023,5.153,2.120,11.322,46.125,6.724,7.219,85.662,AS
90,Vietnam,-0.861,19.190,24.174,8133.27,241.605,-4.983,31.825,30.944,91.713,2.330,14.065,18.363,140.427,46.116,6.987,236.795,AS

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class
0,Albania,-8.609,26.440,30.758,12173.62,100.000,-4.318,26.237,15.804,2.881,17.100,5.272,0.076,194.969,73.716,2.219,11.389,EU,S2
1,Algeria,-16.442,30.544,45.811,11616.72,172.653,-15.267,50.781,34.326,39.963,11.214,5.733,-6.048,237.033,8.733,3.700,165.979,AF,S4
2,Argentina,-2.743,35.366,41.366,23933.89,168.000,-6.001,17.071,14.328,43.132,6.533,-1.633,2.644,825.311,52.563,2.731,642.464,SA,S3
3,Armenia,-2.685,21.494,26.331,11074.41,208.046,-4.837,21.204,18.519,2.990,18.500,9.679,-9.819,149.985,44.133,3.254,10.553,AS,S2
4,Australia,-4.637,34.599,37.387,48757.65,107.650,-2.788,25.910,21.652,23.985,6.058,6.319,2.259,90.165,37.751,2.310,1233.140,OC,S3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-5.165,35.486,39.993,45208.37,100.000,-4.507,17.646,12.481,65.110,5.375,3.765,4.994,92.626,86.022,2.623,2957.230,EU,S3
87,United States,-2.246,31.673,35.205,58385.72,237.002,-3.532,21.201,20.156,320.926,5.275,0.271,5.187,104.691,105.142,2.707,18206.030,NA,S3
88,Uruguay,-0.254,26.607,28.472,22069.82,146.058,-1.865,19.469,19.215,3.467,7.525,-7.755,-8.122,93.157,58.152,0.371,57.874,SA,S2
89,Uzbekistan,1.046,24.325,24.567,6458.15,166.288,-0.242,24.698,25.744,31.023,5.153,2.120,11.322,46.125,6.724,7.219,85.662,AS,S1
90,Vietnam,-0.861,19.190,24.174,8133.27,241.605,-4.983,31.825,30.944,91.713,2.330,14.065,18.363,140.427,46.116,6.987,236.795,AS,S1

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class,debt_class
0,Albania,-8.609,26.440,30.758,12173.62,100.000,-4.318,26.237,15.804,2.881,17.100,5.272,0.076,194.969,73.716,2.219,11.389,EU,S2,Very High
1,Algeria,-16.442,30.544,45.811,11616.72,172.653,-15.267,50.781,34.326,39.963,11.214,5.733,-6.048,237.033,8.733,3.700,165.979,AF,S4,5%-20%
2,Argentina,-2.743,35.366,41.366,23933.89,168.000,-6.001,17.071,14.328,43.132,6.533,-1.633,2.644,825.311,52.563,2.731,642.464,SA,S3,40%-60%
3,Armenia,-2.685,21.494,26.331,11074.41,208.046,-4.837,21.204,18.519,2.990,18.500,9.679,-9.819,149.985,44.133,3.254,10.553,AS,S2,40%-60%
4,Australia,-4.637,34.599,37.387,48757.65,107.650,-2.788,25.910,21.652,23.985,6.058,6.319,2.259,90.165,37.751,2.310,1233.140,OC,S3,20%-40%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-5.165,35.486,39.993,45208.37,100.000,-4.507,17.646,12.481,65.110,5.375,3.765,4.994,92.626,86.022,2.623,2957.230,EU,S3,Very High
87,United States,-2.246,31.673,35.205,58385.72,237.002,-3.532,21.201,20.156,320.926,5.275,0.271,5.187,104.691,105.142,2.707,18206.030,NA,S3,Very High
88,Uruguay,-0.254,26.607,28.472,22069.82,146.058,-1.865,19.469,19.215,3.467,7.525,-7.755,-8.122,93.157,58.152,0.371,57.874,SA,S2,40%-60%
89,Uzbekistan,1.046,24.325,24.567,6458.15,166.288,-0.242,24.698,25.744,31.023,5.153,2.120,11.322,46.125,6.724,7.219,85.662,AS,S1,5%-20%
90,Vietnam,-0.861,19.190,24.174,8133.27,241.605,-4.983,31.825,30.944,91.713,2.330,14.065,18.363,140.427,46.116,6.987,236.795,AS,S1,40%-60%

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,...,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class,debt_class,invest/gdp_class
0,Albania,-8.609,26.440,30.758,12173.62,100.000,-4.318,26.237,15.804,2.881,...,5.272,0.076,194.969,73.716,2.219,11.389,EU,S2,Very High,20%-30%
1,Algeria,-16.442,30.544,45.811,11616.72,172.653,-15.267,50.781,34.326,39.963,...,5.733,-6.048,237.033,8.733,3.700,165.979,AF,S4,5%-20%,>40
2,Argentina,-2.743,35.366,41.366,23933.89,168.000,-6.001,17.071,14.328,43.132,...,-1.633,2.644,825.311,52.563,2.731,642.464,SA,S3,40%-60%,0%-20%
3,Armenia,-2.685,21.494,26.331,11074.41,208.046,-4.837,21.204,18.519,2.990,...,9.679,-9.819,149.985,44.133,3.254,10.553,AS,S2,40%-60%,20%-30%
4,Australia,-4.637,34.599,37.387,48757.65,107.650,-2.788,25.910,21.652,23.985,...,6.319,2.259,90.165,37.751,2.310,1233.140,OC,S3,20%-40%,20%-30%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-5.165,35.486,39.993,45208.37,100.000,-4.507,17.646,12.481,65.110,...,3.765,4.994,92.626,86.022,2.623,2957.230,EU,S3,Very High,0%-20%
87,United States,-2.246,31.673,35.205,58385.72,237.002,-3.532,21.201,20.156,320.926,...,0.271,5.187,104.691,105.142,2.707,18206.030,NA,S3,Very High,20%-30%
88,Uruguay,-0.254,26.607,28.472,22069.82,146.058,-1.865,19.469,19.215,3.467,...,-7.755,-8.122,93.157,58.152,0.371,57.874,SA,S2,40%-60%,0%-20%
89,Uzbekistan,1.046,24.325,24.567,6458.15,166.288,-0.242,24.698,25.744,31.023,...,2.120,11.322,46.125,6.724,7.219,85.662,AS,S1,5%-20%,20%-30%
90,Vietnam,-0.861,19.190,24.174,8133.27,241.605,-4.983,31.825,30.944,91.713,...,14.065,18.363,140.427,46.116,6.987,236.795,AS,S1,40%-60%,30%-40%

,country,continent,spend_class,debt_class,invest/gdp_class,acc_bal,gdp_defl,inflation_ind,gov_rev,gov_expend,...,tot_invest,gross_savings,export_g_s,import_g_s,gross_debt,pop,unemployment,gdp_percap_cons,gdp_cons,gdp_curr
0,Albania,EU,S2,Very High,20%-30%,-8.609,194.969,100.000,26.440,30.758,...,26.237,15.804,5.272,0.076,73.716,2.881,17.100,12173.62,2.219,11.389
1,Algeria,AF,S4,5%-20%,>40,-16.442,237.033,172.653,30.544,45.811,...,50.781,34.326,5.733,-6.048,8.733,39.963,11.214,11616.72,3.700,165.979
2,Argentina,SA,S3,40%-60%,0%-20%,-2.743,825.311,168.000,35.366,41.366,...,17.071,14.328,-1.633,2.644,52.563,43.132,6.533,23933.89,2.731,642.464
3,Armenia,AS,S2,40%-60%,20%-30%,-2.685,149.985,208.046,21.494,26.331,...,21.204,18.519,9.679,-9.819,44.133,2.990,18.500,11074.41,3.254,10.553
4,Australia,OC,S3,20%-40%,20%-30%,-4.637,90.165,107.650,34.599,37.387,...,25.910,21.652,6.319,2.259,37.751,23.985,6.058,48757.65,2.310,1233.140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,EU,S3,Very High,0%-20%,-5.165,92.626,100.000,35.486,39.993,...,17.646,12.481,3.765,4.994,86.022,65.110,5.375,45208.37,2.623,2957.230
87,United States,NA,S3,Very High,20%-30%,-2.246,104.691,237.002,31.673,35.205,...,21.201,20.156,0.271,5.187,105.142,320.926,5.275,58385.72,2.707,18206.030
88,Uruguay,SA,S2,40%-60%,0%-20%,-0.254,93.157,146.058,26.607,28.472,...,19.469,19.215,-7.755,-8.122,58.152,3.467,7.525,22069.82,0.371,57.874
89,Uzbekistan,AS,S1,5%-20%,20%-30%,1.046,46.125,166.288,24.325,24.567,...,24.698,25.744,2.120,11.322,6.724,31.023,5.153,6458.15,7.219,85.662
90,Vietnam,AS,S1,40%-60%,30%-40%,-0.861,140.427,241.605,19.190,24.174,...,31.825,30.944,14.065,18.363,46.116,91.713,2.330,8133.27,6.987,236.795

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent
0,Albania,-7.572,27.642,29.139,12597.30,101.287,-1.498,25.470,16.796,2.876,15.200,10.396,8.300,193.736,73.324,3.315,11.862,EU
1,Algeria,-16.542,28.614,41.665,11732.16,183.699,-13.051,50.778,34.221,40.836,10.498,9.612,-1.236,240.704,20.438,3.200,160.034,AF
2,Argentina,-2.713,34.867,41.522,23189.53,168.270,-6.655,17.663,14.950,43.590,8.467,6.807,3.568,1164.670,53.060,-2.080,556.774,SA
3,Armenia,-1.013,21.416,27.048,11087.77,205.083,-5.632,18.016,17.002,2.993,18.000,17.745,6.342,150.396,51.929,0.195,10.546,AS
4,Australia,-3.277,34.941,37.362,49243.00,109.025,-2.422,24.673,20.886,24.390,5.717,6.675,0.144,91.041,40.581,2.701,1263.920,OC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-5.326,35.872,39.175,45852.77,100.660,-3.303,17.736,12.410,65.648,4.875,3.342,3.532,94.387,85.832,2.263,2732.960,EU
87,United States,-2.127,31.249,35.585,58937.87,240.005,-4.336,20.567,18.907,323.221,4.875,0.407,1.451,105.740,107.165,1.668,18695.100,NA
88,Uruguay,0.829,27.101,29.773,22357.80,160.138,-2.672,17.455,18.283,3.480,7.867,-6.097,-10.259,100.000,56.780,1.690,57.237,SA
89,Uzbekistan,0.249,24.072,23.304,6721.48,180.960,0.769,24.094,24.343,31.575,5.163,4.349,-1.307,50.244,8.192,5.932,85.658,AS
90,Vietnam,0.248,19.067,22.231,8585.48,248.051,-3.164,31.600,31.829,92.695,2.300,11.026,12.863,142.982,47.548,6.690,252.146,AS

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class
0,Albania,-7.572,27.642,29.139,12597.30,101.287,-1.498,25.470,16.796,2.876,15.200,10.396,8.300,193.736,73.324,3.315,11.862,EU,S2
1,Algeria,-16.542,28.614,41.665,11732.16,183.699,-13.051,50.778,34.221,40.836,10.498,9.612,-1.236,240.704,20.438,3.200,160.034,AF,S4
2,Argentina,-2.713,34.867,41.522,23189.53,168.270,-6.655,17.663,14.950,43.590,8.467,6.807,3.568,1164.670,53.060,-2.080,556.774,SA,S4
3,Armenia,-1.013,21.416,27.048,11087.77,205.083,-5.632,18.016,17.002,2.993,18.000,17.745,6.342,150.396,51.929,0.195,10.546,AS,S2
4,Australia,-3.277,34.941,37.362,49243.00,109.025,-2.422,24.673,20.886,24.390,5.717,6.675,0.144,91.041,40.581,2.701,1263.920,OC,S3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-5.326,35.872,39.175,45852.77,100.660,-3.303,17.736,12.410,65.648,4.875,3.342,3.532,94.387,85.832,2.263,2732.960,EU,S3
87,United States,-2.127,31.249,35.585,58937.87,240.005,-4.336,20.567,18.907,323.221,4.875,0.407,1.451,105.740,107.165,1.668,18695.100,NA,S3
88,Uruguay,0.829,27.101,29.773,22357.80,160.138,-2.672,17.455,18.283,3.480,7.867,-6.097,-10.259,100.000,56.780,1.690,57.237,SA,S2
89,Uzbekistan,0.249,24.072,23.304,6721.48,180.960,0.769,24.094,24.343,31.575,5.163,4.349,-1.307,50.244,8.192,5.932,85.658,AS,S1
90,Vietnam,0.248,19.067,22.231,8585.48,248.051,-3.164,31.600,31.829,92.695,2.300,11.026,12.863,142.982,47.548,6.690,252.146,AS,S1

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class,debt_class
0,Albania,-7.572,27.642,29.139,12597.30,101.287,-1.498,25.470,16.796,2.876,15.200,10.396,8.300,193.736,73.324,3.315,11.862,EU,S2,Very High
1,Algeria,-16.542,28.614,41.665,11732.16,183.699,-13.051,50.778,34.221,40.836,10.498,9.612,-1.236,240.704,20.438,3.200,160.034,AF,S4,20%-40%
2,Argentina,-2.713,34.867,41.522,23189.53,168.270,-6.655,17.663,14.950,43.590,8.467,6.807,3.568,1164.670,53.060,-2.080,556.774,SA,S4,40%-60%
3,Armenia,-1.013,21.416,27.048,11087.77,205.083,-5.632,18.016,17.002,2.993,18.000,17.745,6.342,150.396,51.929,0.195,10.546,AS,S2,40%-60%
4,Australia,-3.277,34.941,37.362,49243.00,109.025,-2.422,24.673,20.886,24.390,5.717,6.675,0.144,91.041,40.581,2.701,1263.920,OC,S3,40%-60%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-5.326,35.872,39.175,45852.77,100.660,-3.303,17.736,12.410,65.648,4.875,3.342,3.532,94.387,85.832,2.263,2732.960,EU,S3,Very High
87,United States,-2.127,31.249,35.585,58937.87,240.005,-4.336,20.567,18.907,323.221,4.875,0.407,1.451,105.740,107.165,1.668,18695.100,NA,S3,Very High
88,Uruguay,0.829,27.101,29.773,22357.80,160.138,-2.672,17.455,18.283,3.480,7.867,-6.097,-10.259,100.000,56.780,1.690,57.237,SA,S2,40%-60%
89,Uzbekistan,0.249,24.072,23.304,6721.48,180.960,0.769,24.094,24.343,31.575,5.163,4.349,-1.307,50.244,8.192,5.932,85.658,AS,S1,5%-20%
90,Vietnam,0.248,19.067,22.231,8585.48,248.051,-3.164,31.600,31.829,92.695,2.300,11.026,12.863,142.982,47.548,6.690,252.146,AS,S1,40%-60%

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,...,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class,debt_class,invest/gdp_class
0,Albania,-7.572,27.642,29.139,12597.30,101.287,-1.498,25.470,16.796,2.876,...,10.396,8.300,193.736,73.324,3.315,11.862,EU,S2,Very High,20%-30%
1,Algeria,-16.542,28.614,41.665,11732.16,183.699,-13.051,50.778,34.221,40.836,...,9.612,-1.236,240.704,20.438,3.200,160.034,AF,S4,20%-40%,>40
2,Argentina,-2.713,34.867,41.522,23189.53,168.270,-6.655,17.663,14.950,43.590,...,6.807,3.568,1164.670,53.060,-2.080,556.774,SA,S4,40%-60%,0%-20%
3,Armenia,-1.013,21.416,27.048,11087.77,205.083,-5.632,18.016,17.002,2.993,...,17.745,6.342,150.396,51.929,0.195,10.546,AS,S2,40%-60%,0%-20%
4,Australia,-3.277,34.941,37.362,49243.00,109.025,-2.422,24.673,20.886,24.390,...,6.675,0.144,91.041,40.581,2.701,1263.920,OC,S3,40%-60%,20%-30%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-5.326,35.872,39.175,45852.77,100.660,-3.303,17.736,12.410,65.648,...,3.342,3.532,94.387,85.832,2.263,2732.960,EU,S3,Very High,0%-20%
87,United States,-2.127,31.249,35.585,58937.87,240.005,-4.336,20.567,18.907,323.221,...,0.407,1.451,105.740,107.165,1.668,18695.100,NA,S3,Very High,20%-30%
88,Uruguay,0.829,27.101,29.773,22357.80,160.138,-2.672,17.455,18.283,3.480,...,-6.097,-10.259,100.000,56.780,1.690,57.237,SA,S2,40%-60%,0%-20%
89,Uzbekistan,0.249,24.072,23.304,6721.48,180.960,0.769,24.094,24.343,31.575,...,4.349,-1.307,50.244,8.192,5.932,85.658,AS,S1,5%-20%,20%-30%
90,Vietnam,0.248,19.067,22.231,8585.48,248.051,-3.164,31.600,31.829,92.695,...,11.026,12.863,142.982,47.548,6.690,252.146,AS,S1,40%-60%,30%-40%

,country,continent,spend_class,debt_class,invest/gdp_class,acc_bal,gdp_defl,inflation_ind,gov_rev,gov_expend,...,tot_invest,gross_savings,export_g_s,import_g_s,gross_debt,pop,unemployment,gdp_percap_cons,gdp_cons,gdp_curr
0,Albania,EU,S2,Very High,20%-30%,-7.572,193.736,101.287,27.642,29.139,...,25.470,16.796,10.396,8.300,73.324,2.876,15.200,12597.30,3.315,11.862
1,Algeria,AF,S4,20%-40%,>40,-16.542,240.704,183.699,28.614,41.665,...,50.778,34.221,9.612,-1.236,20.438,40.836,10.498,11732.16,3.200,160.034
2,Argentina,SA,S4,40%-60%,0%-20%,-2.713,1164.670,168.270,34.867,41.522,...,17.663,14.950,6.807,3.568,53.060,43.590,8.467,23189.53,-2.080,556.774
3,Armenia,AS,S2,40%-60%,0%-20%,-1.013,150.396,205.083,21.416,27.048,...,18.016,17.002,17.745,6.342,51.929,2.993,18.000,11087.77,0.195,10.546
4,Australia,OC,S3,40%-60%,20%-30%,-3.277,91.041,109.025,34.941,37.362,...,24.673,20.886,6.675,0.144,40.581,24.390,5.717,49243.00,2.701,1263.920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,EU,S3,Very High,0%-20%,-5.326,94.387,100.660,35.872,39.175,...,17.736,12.410,3.342,3.532,85.832,65.648,4.875,45852.77,2.263,2732.960
87,United States,NA,S3,Very High,20%-30%,-2.127,105.740,240.005,31.249,35.585,...,20.567,18.907,0.407,1.451,107.165,323.221,4.875,58937.87,1.668,18695.100
88,Uruguay,SA,S2,40%-60%,0%-20%,0.829,100.000,160.138,27.101,29.773,...,17.455,18.283,-6.097,-10.259,56.780,3.480,7.867,22357.80,1.690,57.237
89,Uzbekistan,AS,S1,5%-20%,20%-30%,0.249,50.244,180.960,24.072,23.304,...,24.094,24.343,4.349,-1.307,8.192,31.575,5.163,6721.48,5.932,85.658
90,Vietnam,AS,S1,40%-60%,30%-40%,0.248,142.982,248.051,19.067,22.231,...,31.600,31.829,11.026,12.863,47.548,92.695,2.300,8585.48,6.690,252.146

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent
0,Albania,-7.492,27.756,29.372,13039.70,103.297,-1.616,24.672,17.085,2.884,13.700,10.100,5.993,196.547,71.895,3.802,13.053,EU
1,Algeria,-13.120,32.040,38.581,11644.06,193.970,-6.541,48.544,35.424,41.721,11.709,0.042,-0.833,255.835,26.808,1.400,170.207,AF
2,Argentina,-4.838,34.428,41.121,23597.12,211.473,-6.693,18.213,13.375,44.045,8.350,-0.132,14.235,1467.560,57.028,2.819,643.861,SA
3,Armenia,-1.521,21.242,26.027,11974.03,207.522,-4.785,18.422,16.901,2.979,17.800,13.564,22.152,153.605,53.704,7.518,11.527,AS
4,Australia,-2.573,35.144,36.862,49633.24,111.200,-1.718,24.282,22.027,24.773,5.592,3.439,7.753,94.332,41.170,2.378,1381.990,OC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-3.631,36.431,38.783,46553.49,103.361,-2.353,18.189,14.558,66.040,4.425,5.654,2.923,96.104,85.146,2.134,2701.270,EU
87,United States,-1.857,30.835,35.461,59885.71,245.121,-4.626,20.790,19.486,325.280,4.358,4.077,4.445,107.747,106.204,2.255,19479.630,NA
88,Uruguay,0.012,27.544,30.051,22637.31,170.095,-2.507,15.829,15.841,3.493,7.925,3.528,3.896,104.987,56.520,1.628,64.234,SA
89,Uzbekistan,2.422,23.557,22.352,6897.81,206.070,1.204,29.526,31.948,32.121,5.830,14.776,3.634,59.822,19.274,4.395,61.018,AS
90,Vietnam,-0.596,19.565,21.529,9085.61,256.785,-1.964,31.940,31.327,93.672,2.240,17.235,18.392,149.220,46.320,6.940,277.071,AS

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class
0,Albania,-7.492,27.756,29.372,13039.70,103.297,-1.616,24.672,17.085,2.884,13.700,10.100,5.993,196.547,71.895,3.802,13.053,EU,S2
1,Algeria,-13.120,32.040,38.581,11644.06,193.970,-6.541,48.544,35.424,41.721,11.709,0.042,-0.833,255.835,26.808,1.400,170.207,AF,S3
2,Argentina,-4.838,34.428,41.121,23597.12,211.473,-6.693,18.213,13.375,44.045,8.350,-0.132,14.235,1467.560,57.028,2.819,643.861,SA,S4
3,Armenia,-1.521,21.242,26.027,11974.03,207.522,-4.785,18.422,16.901,2.979,17.800,13.564,22.152,153.605,53.704,7.518,11.527,AS,S2
4,Australia,-2.573,35.144,36.862,49633.24,111.200,-1.718,24.282,22.027,24.773,5.592,3.439,7.753,94.332,41.170,2.378,1381.990,OC,S3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-3.631,36.431,38.783,46553.49,103.361,-2.353,18.189,14.558,66.040,4.425,5.654,2.923,96.104,85.146,2.134,2701.270,EU,S3
87,United States,-1.857,30.835,35.461,59885.71,245.121,-4.626,20.790,19.486,325.280,4.358,4.077,4.445,107.747,106.204,2.255,19479.630,NA,S3
88,Uruguay,0.012,27.544,30.051,22637.31,170.095,-2.507,15.829,15.841,3.493,7.925,3.528,3.896,104.987,56.520,1.628,64.234,SA,S2
89,Uzbekistan,2.422,23.557,22.352,6897.81,206.070,1.204,29.526,31.948,32.121,5.830,14.776,3.634,59.822,19.274,4.395,61.018,AS,S1
90,Vietnam,-0.596,19.565,21.529,9085.61,256.785,-1.964,31.940,31.327,93.672,2.240,17.235,18.392,149.220,46.320,6.940,277.071,AS,S1

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class,debt_class
0,Albania,-7.492,27.756,29.372,13039.70,103.297,-1.616,24.672,17.085,2.884,13.700,10.100,5.993,196.547,71.895,3.802,13.053,EU,S2,Very High
1,Algeria,-13.120,32.040,38.581,11644.06,193.970,-6.541,48.544,35.424,41.721,11.709,0.042,-0.833,255.835,26.808,1.400,170.207,AF,S3,20%-40%
2,Argentina,-4.838,34.428,41.121,23597.12,211.473,-6.693,18.213,13.375,44.045,8.350,-0.132,14.235,1467.560,57.028,2.819,643.861,SA,S4,40%-60%
3,Armenia,-1.521,21.242,26.027,11974.03,207.522,-4.785,18.422,16.901,2.979,17.800,13.564,22.152,153.605,53.704,7.518,11.527,AS,S2,40%-60%
4,Australia,-2.573,35.144,36.862,49633.24,111.200,-1.718,24.282,22.027,24.773,5.592,3.439,7.753,94.332,41.170,2.378,1381.990,OC,S3,40%-60%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-3.631,36.431,38.783,46553.49,103.361,-2.353,18.189,14.558,66.040,4.425,5.654,2.923,96.104,85.146,2.134,2701.270,EU,S3,Very High
87,United States,-1.857,30.835,35.461,59885.71,245.121,-4.626,20.790,19.486,325.280,4.358,4.077,4.445,107.747,106.204,2.255,19479.630,NA,S3,Very High
88,Uruguay,0.012,27.544,30.051,22637.31,170.095,-2.507,15.829,15.841,3.493,7.925,3.528,3.896,104.987,56.520,1.628,64.234,SA,S2,40%-60%
89,Uzbekistan,2.422,23.557,22.352,6897.81,206.070,1.204,29.526,31.948,32.121,5.830,14.776,3.634,59.822,19.274,4.395,61.018,AS,S1,5%-20%
90,Vietnam,-0.596,19.565,21.529,9085.61,256.785,-1.964,31.940,31.327,93.672,2.240,17.235,18.392,149.220,46.320,6.940,277.071,AS,S1,40%-60%

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,...,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class,debt_class,invest/gdp_class
0,Albania,-7.492,27.756,29.372,13039.70,103.297,-1.616,24.672,17.085,2.884,...,10.100,5.993,196.547,71.895,3.802,13.053,EU,S2,Very High,20%-30%
1,Algeria,-13.120,32.040,38.581,11644.06,193.970,-6.541,48.544,35.424,41.721,...,0.042,-0.833,255.835,26.808,1.400,170.207,AF,S3,20%-40%,>40
2,Argentina,-4.838,34.428,41.121,23597.12,211.473,-6.693,18.213,13.375,44.045,...,-0.132,14.235,1467.560,57.028,2.819,643.861,SA,S4,40%-60%,0%-20%
3,Armenia,-1.521,21.242,26.027,11974.03,207.522,-4.785,18.422,16.901,2.979,...,13.564,22.152,153.605,53.704,7.518,11.527,AS,S2,40%-60%,0%-20%
4,Australia,-2.573,35.144,36.862,49633.24,111.200,-1.718,24.282,22.027,24.773,...,3.439,7.753,94.332,41.170,2.378,1381.990,OC,S3,40%-60%,20%-30%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-3.631,36.431,38.783,46553.49,103.361,-2.353,18.189,14.558,66.040,...,5.654,2.923,96.104,85.146,2.134,2701.270,EU,S3,Very High,0%-20%
87,United States,-1.857,30.835,35.461,59885.71,245.121,-4.626,20.790,19.486,325.280,...,4.077,4.445,107.747,106.204,2.255,19479.630,NA,S3,Very High,20%-30%
88,Uruguay,0.012,27.544,30.051,22637.31,170.095,-2.507,15.829,15.841,3.493,...,3.528,3.896,104.987,56.520,1.628,64.234,SA,S2,40%-60%,0%-20%
89,Uzbekistan,2.422,23.557,22.352,6897.81,206.070,1.204,29.526,31.948,32.121,...,14.776,3.634,59.822,19.274,4.395,61.018,AS,S1,5%-20%,20%-30%
90,Vietnam,-0.596,19.565,21.529,9085.61,256.785,-1.964,31.940,31.327,93.672,...,17.235,18.392,149.220,46.320,6.940,277.071,AS,S1,40%-60%,30%-40%

,country,continent,spend_class,debt_class,invest/gdp_class,acc_bal,gdp_defl,inflation_ind,gov_rev,gov_expend,...,tot_invest,gross_savings,export_g_s,import_g_s,gross_debt,pop,unemployment,gdp_percap_cons,gdp_cons,gdp_curr
0,Albania,EU,S2,Very High,20%-30%,-7.492,196.547,103.297,27.756,29.372,...,24.672,17.085,10.100,5.993,71.895,2.884,13.700,13039.70,3.802,13.053
1,Algeria,AF,S3,20%-40%,>40,-13.120,255.835,193.970,32.040,38.581,...,48.544,35.424,0.042,-0.833,26.808,41.721,11.709,11644.06,1.400,170.207
2,Argentina,SA,S4,40%-60%,0%-20%,-4.838,1467.560,211.473,34.428,41.121,...,18.213,13.375,-0.132,14.235,57.028,44.045,8.350,23597.12,2.819,643.861
3,Armenia,AS,S2,40%-60%,0%-20%,-1.521,153.605,207.522,21.242,26.027,...,18.422,16.901,13.564,22.152,53.704,2.979,17.800,11974.03,7.518,11.527
4,Australia,OC,S3,40%-60%,20%-30%,-2.573,94.332,111.200,35.144,36.862,...,24.282,22.027,3.439,7.753,41.170,24.773,5.592,49633.24,2.378,1381.990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,EU,S3,Very High,0%-20%,-3.631,96.104,103.361,36.431,38.783,...,18.189,14.558,5.654,2.923,85.146,66.040,4.425,46553.49,2.134,2701.270
87,United States,NA,S3,Very High,20%-30%,-1.857,107.747,245.121,30.835,35.461,...,20.790,19.486,4.077,4.445,106.204,325.280,4.358,59885.71,2.255,19479.630
88,Uruguay,SA,S2,40%-60%,0%-20%,0.012,104.987,170.095,27.544,30.051,...,15.829,15.841,3.528,3.896,56.520,3.493,7.925,22637.31,1.628,64.234
89,Uzbekistan,AS,S1,5%-20%,20%-30%,2.422,59.822,206.070,23.557,22.352,...,29.526,31.948,14.776,3.634,19.274,32.121,5.830,6897.81,4.395,61.018
90,Vietnam,AS,S1,40%-60%,30%-40%,-0.596,149.220,256.785,19.565,21.529,...,31.940,31.327,17.235,18.392,46.320,93.672,2.240,9085.61,6.940,277.071

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent
0,Albania,-6.754,27.485,28.802,13570.55,105.393,-1.317,24.118,17.109,2.883,12.300,3.469,5.765,199.442,69.466,4.019,15.157,EU
1,Algeria,-9.645,33.380,37.805,11546.61,202.253,-4.426,47.279,37.634,42.578,11.731,-7.913,-1.533,273.909,38.256,1.200,175.372,AF
2,Argentina,-5.165,33.508,38.949,22747.24,283.959,-5.441,16.614,11.449,44.495,9.200,-0.264,-5.591,2084.430,85.246,-2.617,524.431,SA
3,Armenia,-7.030,22.298,24.050,12644.05,212.681,-1.752,22.400,15.369,2.969,19.000,9.045,13.181,157.849,51.233,5.225,12.458,AS
4,Australia,-2.140,35.732,36.991,50201.49,113.350,-1.259,24.200,21.991,25.171,5.300,5.080,4.323,96.457,41.764,2.770,1416.980,OC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-3.878,36.279,38.439,47039.99,105.922,-2.159,17.867,13.990,66.436,4.075,2.777,3.072,98.025,84.490,1.651,2904.510,EU
87,United States,-2.135,30.137,35.575,61305.19,251.099,-5.439,21.145,19.611,327.023,3.892,2.812,4.099,110.321,107.476,2.919,20527.150,NA
88,Uruguay,-0.413,28.820,30.691,22662.60,183.033,-1.871,14.953,14.540,3.506,8.367,-0.753,-0.845,112.443,58.567,0.478,64.515,SA
89,Uzbekistan,-6.829,26.958,24.933,7147.86,242.182,2.024,42.351,35.522,32.657,9.347,11.760,39.622,75.964,19.714,5.355,52.618,AS
90,Vietnam,1.903,19.547,20.573,9637.22,265.875,-1.026,31.888,33.775,94.666,2.190,10.892,8.813,154.316,43.712,7.197,303.091,AS

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class
0,Albania,-6.754,27.485,28.802,13570.55,105.393,-1.317,24.118,17.109,2.883,12.300,3.469,5.765,199.442,69.466,4.019,15.157,EU,S2
1,Algeria,-9.645,33.380,37.805,11546.61,202.253,-4.426,47.279,37.634,42.578,11.731,-7.913,-1.533,273.909,38.256,1.200,175.372,AF,S3
2,Argentina,-5.165,33.508,38.949,22747.24,283.959,-5.441,16.614,11.449,44.495,9.200,-0.264,-5.591,2084.430,85.246,-2.617,524.431,SA,S3
3,Armenia,-7.030,22.298,24.050,12644.05,212.681,-1.752,22.400,15.369,2.969,19.000,9.045,13.181,157.849,51.233,5.225,12.458,AS,S1
4,Australia,-2.140,35.732,36.991,50201.49,113.350,-1.259,24.200,21.991,25.171,5.300,5.080,4.323,96.457,41.764,2.770,1416.980,OC,S3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-3.878,36.279,38.439,47039.99,105.922,-2.159,17.867,13.990,66.436,4.075,2.777,3.072,98.025,84.490,1.651,2904.510,EU,S3
87,United States,-2.135,30.137,35.575,61305.19,251.099,-5.439,21.145,19.611,327.023,3.892,2.812,4.099,110.321,107.476,2.919,20527.150,NA,S3
88,Uruguay,-0.413,28.820,30.691,22662.60,183.033,-1.871,14.953,14.540,3.506,8.367,-0.753,-0.845,112.443,58.567,0.478,64.515,SA,S2
89,Uzbekistan,-6.829,26.958,24.933,7147.86,242.182,2.024,42.351,35.522,32.657,9.347,11.760,39.622,75.964,19.714,5.355,52.618,AS,S1
90,Vietnam,1.903,19.547,20.573,9637.22,265.875,-1.026,31.888,33.775,94.666,2.190,10.892,8.813,154.316,43.712,7.197,303.091,AS,S1

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class,debt_class
0,Albania,-6.754,27.485,28.802,13570.55,105.393,-1.317,24.118,17.109,2.883,12.300,3.469,5.765,199.442,69.466,4.019,15.157,EU,S2,Very High
1,Algeria,-9.645,33.380,37.805,11546.61,202.253,-4.426,47.279,37.634,42.578,11.731,-7.913,-1.533,273.909,38.256,1.200,175.372,AF,S3,20%-40%
2,Argentina,-5.165,33.508,38.949,22747.24,283.959,-5.441,16.614,11.449,44.495,9.200,-0.264,-5.591,2084.430,85.246,-2.617,524.431,SA,S3,Very High
3,Armenia,-7.030,22.298,24.050,12644.05,212.681,-1.752,22.400,15.369,2.969,19.000,9.045,13.181,157.849,51.233,5.225,12.458,AS,S1,40%-60%
4,Australia,-2.140,35.732,36.991,50201.49,113.350,-1.259,24.200,21.991,25.171,5.300,5.080,4.323,96.457,41.764,2.770,1416.980,OC,S3,40%-60%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-3.878,36.279,38.439,47039.99,105.922,-2.159,17.867,13.990,66.436,4.075,2.777,3.072,98.025,84.490,1.651,2904.510,EU,S3,Very High
87,United States,-2.135,30.137,35.575,61305.19,251.099,-5.439,21.145,19.611,327.023,3.892,2.812,4.099,110.321,107.476,2.919,20527.150,NA,S3,Very High
88,Uruguay,-0.413,28.820,30.691,22662.60,183.033,-1.871,14.953,14.540,3.506,8.367,-0.753,-0.845,112.443,58.567,0.478,64.515,SA,S2,40%-60%
89,Uzbekistan,-6.829,26.958,24.933,7147.86,242.182,2.024,42.351,35.522,32.657,9.347,11.760,39.622,75.964,19.714,5.355,52.618,AS,S1,5%-20%
90,Vietnam,1.903,19.547,20.573,9637.22,265.875,-1.026,31.888,33.775,94.666,2.190,10.892,8.813,154.316,43.712,7.197,303.091,AS,S1,40%-60%

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,...,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class,debt_class,invest/gdp_class
0,Albania,-6.754,27.485,28.802,13570.55,105.393,-1.317,24.118,17.109,2.883,...,3.469,5.765,199.442,69.466,4.019,15.157,EU,S2,Very High,20%-30%
1,Algeria,-9.645,33.380,37.805,11546.61,202.253,-4.426,47.279,37.634,42.578,...,-7.913,-1.533,273.909,38.256,1.200,175.372,AF,S3,20%-40%,>40
2,Argentina,-5.165,33.508,38.949,22747.24,283.959,-5.441,16.614,11.449,44.495,...,-0.264,-5.591,2084.430,85.246,-2.617,524.431,SA,S3,Very High,0%-20%
3,Armenia,-7.030,22.298,24.050,12644.05,212.681,-1.752,22.400,15.369,2.969,...,9.045,13.181,157.849,51.233,5.225,12.458,AS,S1,40%-60%,20%-30%
4,Australia,-2.140,35.732,36.991,50201.49,113.350,-1.259,24.200,21.991,25.171,...,5.080,4.323,96.457,41.764,2.770,1416.980,OC,S3,40%-60%,20%-30%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-3.878,36.279,38.439,47039.99,105.922,-2.159,17.867,13.990,66.436,...,2.777,3.072,98.025,84.490,1.651,2904.510,EU,S3,Very High,0%-20%
87,United States,-2.135,30.137,35.575,61305.19,251.099,-5.439,21.145,19.611,327.023,...,2.812,4.099,110.321,107.476,2.919,20527.150,NA,S3,Very High,20%-30%
88,Uruguay,-0.413,28.820,30.691,22662.60,183.033,-1.871,14.953,14.540,3.506,...,-0.753,-0.845,112.443,58.567,0.478,64.515,SA,S2,40%-60%,0%-20%
89,Uzbekistan,-6.829,26.958,24.933,7147.86,242.182,2.024,42.351,35.522,32.657,...,11.760,39.622,75.964,19.714,5.355,52.618,AS,S1,5%-20%,>40
90,Vietnam,1.903,19.547,20.573,9637.22,265.875,-1.026,31.888,33.775,94.666,...,10.892,8.813,154.316,43.712,7.197,303.091,AS,S1,40%-60%,30%-40%

,country,continent,spend_class,debt_class,invest/gdp_class,acc_bal,gdp_defl,inflation_ind,gov_rev,gov_expend,...,tot_invest,gross_savings,export_g_s,import_g_s,gross_debt,pop,unemployment,gdp_percap_cons,gdp_cons,gdp_curr
0,Albania,EU,S2,Very High,20%-30%,-6.754,199.442,105.393,27.485,28.802,...,24.118,17.109,3.469,5.765,69.466,2.883,12.300,13570.55,4.019,15.157
1,Algeria,AF,S3,20%-40%,>40,-9.645,273.909,202.253,33.380,37.805,...,47.279,37.634,-7.913,-1.533,38.256,42.578,11.731,11546.61,1.200,175.372
2,Argentina,SA,S3,Very High,0%-20%,-5.165,2084.430,283.959,33.508,38.949,...,16.614,11.449,-0.264,-5.591,85.246,44.495,9.200,22747.24,-2.617,524.431
3,Armenia,AS,S1,40%-60%,20%-30%,-7.030,157.849,212.681,22.298,24.050,...,22.400,15.369,9.045,13.181,51.233,2.969,19.000,12644.05,5.225,12.458
4,Australia,OC,S3,40%-60%,20%-30%,-2.140,96.457,113.350,35.732,36.991,...,24.200,21.991,5.080,4.323,41.764,25.171,5.300,50201.49,2.770,1416.980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,EU,S3,Very High,0%-20%,-3.878,98.025,105.922,36.279,38.439,...,17.867,13.990,2.777,3.072,84.490,66.436,4.075,47039.99,1.651,2904.510
87,United States,NA,S3,Very High,20%-30%,-2.135,110.321,251.099,30.137,35.575,...,21.145,19.611,2.812,4.099,107.476,327.023,3.892,61305.19,2.919,20527.150
88,Uruguay,SA,S2,40%-60%,0%-20%,-0.413,112.443,183.033,28.820,30.691,...,14.953,14.540,-0.753,-0.845,58.567,3.506,8.367,22662.60,0.478,64.515
89,Uzbekistan,AS,S1,5%-20%,>40,-6.829,75.964,242.182,26.958,24.933,...,42.351,35.522,11.760,39.622,19.714,32.657,9.347,7147.86,5.355,52.618
90,Vietnam,AS,S1,40%-60%,30%-40%,1.903,154.316,265.875,19.547,20.573,...,31.888,33.775,10.892,8.813,43.712,94.666,2.190,9637.22,7.197,303.091

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent
0,Albania,-7.571,27.209,29.153,13862.63,106.880,-1.944,23.032,14.742,2.881,11.470,1.695,4.716,201.949,67.285,2.088,15.399,EU
1,Algeria,-9.911,32.316,37.895,11412.23,206.200,-5.579,45.991,36.080,43.424,11.383,-2.954,-9.686,271.416,46.208,0.800,171.070,AF
2,Argentina,-0.821,33.308,37.703,22066.10,436.015,-4.395,14.917,14.097,44.939,9.825,12.155,-21.107,3145.860,88.835,-2.026,451.815,SA
3,Armenia,-7.359,23.925,24.902,13637.87,215.749,-0.977,17.409,10.050,2.963,18.300,16.507,13.339,159.485,50.086,7.631,13.619,AS
4,Australia,0.606,34.642,39.021,50428.69,115.150,-4.379,22.568,23.280,25.558,5.158,3.374,-1.450,99.560,46.797,1.995,1386.640,OC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-2.668,36.038,38.248,47567.99,107.819,-2.209,18.007,15.340,66.797,3.825,3.358,2.927,100.000,83.850,1.672,2880.360,EU
87,United States,-2.209,30.080,35.808,62417.55,255.647,-5.728,21.365,19.446,328.547,3.675,-0.067,1.150,112.294,108.800,2.289,21372.600,NA
88,Uruguay,1.601,28.312,31.070,22660.77,197.460,-2.758,14.639,16.240,3.519,8.925,-2.036,-3.228,122.026,60.456,0.350,61.231,SA
89,Uzbekistan,-5.619,27.880,27.285,7419.93,277.361,0.595,40.522,34.904,33.256,8.976,16.188,15.958,89.569,28.360,5.710,59.907,AS
90,Vietnam,3.711,19.648,20.050,10131.71,273.311,-0.402,31.802,35.497,96.484,2.170,6.715,6.944,157.193,41.292,7.150,327.873,AS

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class
0,Albania,-7.571,27.209,29.153,13862.63,106.880,-1.944,23.032,14.742,2.881,11.470,1.695,4.716,201.949,67.285,2.088,15.399,EU,S2
1,Algeria,-9.911,32.316,37.895,11412.23,206.200,-5.579,45.991,36.080,43.424,11.383,-2.954,-9.686,271.416,46.208,0.800,171.070,AF,S3
2,Argentina,-0.821,33.308,37.703,22066.10,436.015,-4.395,14.917,14.097,44.939,9.825,12.155,-21.107,3145.860,88.835,-2.026,451.815,SA,S3
3,Armenia,-7.359,23.925,24.902,13637.87,215.749,-0.977,17.409,10.050,2.963,18.300,16.507,13.339,159.485,50.086,7.631,13.619,AS,S1
4,Australia,0.606,34.642,39.021,50428.69,115.150,-4.379,22.568,23.280,25.558,5.158,3.374,-1.450,99.560,46.797,1.995,1386.640,OC,S3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-2.668,36.038,38.248,47567.99,107.819,-2.209,18.007,15.340,66.797,3.825,3.358,2.927,100.000,83.850,1.672,2880.360,EU,S3
87,United States,-2.209,30.080,35.808,62417.55,255.647,-5.728,21.365,19.446,328.547,3.675,-0.067,1.150,112.294,108.800,2.289,21372.600,NA,S3
88,Uruguay,1.601,28.312,31.070,22660.77,197.460,-2.758,14.639,16.240,3.519,8.925,-2.036,-3.228,122.026,60.456,0.350,61.231,SA,S2
89,Uzbekistan,-5.619,27.880,27.285,7419.93,277.361,0.595,40.522,34.904,33.256,8.976,16.188,15.958,89.569,28.360,5.710,59.907,AS,S2
90,Vietnam,3.711,19.648,20.050,10131.71,273.311,-0.402,31.802,35.497,96.484,2.170,6.715,6.944,157.193,41.292,7.150,327.873,AS,S1

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class,debt_class
0,Albania,-7.571,27.209,29.153,13862.63,106.880,-1.944,23.032,14.742,2.881,11.470,1.695,4.716,201.949,67.285,2.088,15.399,EU,S2,Very High
1,Algeria,-9.911,32.316,37.895,11412.23,206.200,-5.579,45.991,36.080,43.424,11.383,-2.954,-9.686,271.416,46.208,0.800,171.070,AF,S3,40%-60%
2,Argentina,-0.821,33.308,37.703,22066.10,436.015,-4.395,14.917,14.097,44.939,9.825,12.155,-21.107,3145.860,88.835,-2.026,451.815,SA,S3,Very High
3,Armenia,-7.359,23.925,24.902,13637.87,215.749,-0.977,17.409,10.050,2.963,18.300,16.507,13.339,159.485,50.086,7.631,13.619,AS,S1,40%-60%
4,Australia,0.606,34.642,39.021,50428.69,115.150,-4.379,22.568,23.280,25.558,5.158,3.374,-1.450,99.560,46.797,1.995,1386.640,OC,S3,40%-60%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-2.668,36.038,38.248,47567.99,107.819,-2.209,18.007,15.340,66.797,3.825,3.358,2.927,100.000,83.850,1.672,2880.360,EU,S3,Very High
87,United States,-2.209,30.080,35.808,62417.55,255.647,-5.728,21.365,19.446,328.547,3.675,-0.067,1.150,112.294,108.800,2.289,21372.600,NA,S3,Very High
88,Uruguay,1.601,28.312,31.070,22660.77,197.460,-2.758,14.639,16.240,3.519,8.925,-2.036,-3.228,122.026,60.456,0.350,61.231,SA,S2,Very High
89,Uzbekistan,-5.619,27.880,27.285,7419.93,277.361,0.595,40.522,34.904,33.256,8.976,16.188,15.958,89.569,28.360,5.710,59.907,AS,S2,20%-40%
90,Vietnam,3.711,19.648,20.050,10131.71,273.311,-0.402,31.802,35.497,96.484,2.170,6.715,6.944,157.193,41.292,7.150,327.873,AS,S1,40%-60%

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,...,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class,debt_class,invest/gdp_class
0,Albania,-7.571,27.209,29.153,13862.63,106.880,-1.944,23.032,14.742,2.881,...,1.695,4.716,201.949,67.285,2.088,15.399,EU,S2,Very High,20%-30%
1,Algeria,-9.911,32.316,37.895,11412.23,206.200,-5.579,45.991,36.080,43.424,...,-2.954,-9.686,271.416,46.208,0.800,171.070,AF,S3,40%-60%,>40
2,Argentina,-0.821,33.308,37.703,22066.10,436.015,-4.395,14.917,14.097,44.939,...,12.155,-21.107,3145.860,88.835,-2.026,451.815,SA,S3,Very High,0%-20%
3,Armenia,-7.359,23.925,24.902,13637.87,215.749,-0.977,17.409,10.050,2.963,...,16.507,13.339,159.485,50.086,7.631,13.619,AS,S1,40%-60%,0%-20%
4,Australia,0.606,34.642,39.021,50428.69,115.150,-4.379,22.568,23.280,25.558,...,3.374,-1.450,99.560,46.797,1.995,1386.640,OC,S3,40%-60%,20%-30%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-2.668,36.038,38.248,47567.99,107.819,-2.209,18.007,15.340,66.797,...,3.358,2.927,100.000,83.850,1.672,2880.360,EU,S3,Very High,0%-20%
87,United States,-2.209,30.080,35.808,62417.55,255.647,-5.728,21.365,19.446,328.547,...,-0.067,1.150,112.294,108.800,2.289,21372.600,NA,S3,Very High,20%-30%
88,Uruguay,1.601,28.312,31.070,22660.77,197.460,-2.758,14.639,16.240,3.519,...,-2.036,-3.228,122.026,60.456,0.350,61.231,SA,S2,Very High,0%-20%
89,Uzbekistan,-5.619,27.880,27.285,7419.93,277.361,0.595,40.522,34.904,33.256,...,16.188,15.958,89.569,28.360,5.710,59.907,AS,S2,20%-40%,>40
90,Vietnam,3.711,19.648,20.050,10131.71,273.311,-0.402,31.802,35.497,96.484,...,6.715,6.944,157.193,41.292,7.150,327.873,AS,S1,40%-60%,30%-40%

,country,continent,spend_class,debt_class,invest/gdp_class,acc_bal,gdp_defl,inflation_ind,gov_rev,gov_expend,...,tot_invest,gross_savings,export_g_s,import_g_s,gross_debt,pop,unemployment,gdp_percap_cons,gdp_cons,gdp_curr
0,Albania,EU,S2,Very High,20%-30%,-7.571,201.949,106.880,27.209,29.153,...,23.032,14.742,1.695,4.716,67.285,2.881,11.470,13862.63,2.088,15.399
1,Algeria,AF,S3,40%-60%,>40,-9.911,271.416,206.200,32.316,37.895,...,45.991,36.080,-2.954,-9.686,46.208,43.424,11.383,11412.23,0.800,171.070
2,Argentina,SA,S3,Very High,0%-20%,-0.821,3145.860,436.015,33.308,37.703,...,14.917,14.097,12.155,-21.107,88.835,44.939,9.825,22066.10,-2.026,451.815
3,Armenia,AS,S1,40%-60%,0%-20%,-7.359,159.485,215.749,23.925,24.902,...,17.409,10.050,16.507,13.339,50.086,2.963,18.300,13637.87,7.631,13.619
4,Australia,OC,S3,40%-60%,20%-30%,0.606,99.560,115.150,34.642,39.021,...,22.568,23.280,3.374,-1.450,46.797,25.558,5.158,50428.69,1.995,1386.640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,EU,S3,Very High,0%-20%,-2.668,100.000,107.819,36.038,38.248,...,18.007,15.340,3.358,2.927,83.850,66.797,3.825,47567.99,1.672,2880.360
87,United States,NA,S3,Very High,20%-30%,-2.209,112.294,255.647,30.080,35.808,...,21.365,19.446,-0.067,1.150,108.800,328.547,3.675,62417.55,2.289,21372.600
88,Uruguay,SA,S2,Very High,0%-20%,1.601,122.026,197.460,28.312,31.070,...,14.639,16.240,-2.036,-3.228,60.456,3.519,8.925,22660.77,0.350,61.231
89,Uzbekistan,AS,S2,20%-40%,>40,-5.619,89.569,277.361,27.880,27.285,...,40.522,34.904,16.188,15.958,28.360,33.256,8.976,7419.93,5.710,59.907
90,Vietnam,AS,S1,40%-60%,30%-40%,3.711,157.193,273.311,19.648,20.050,...,31.802,35.497,6.715,6.944,41.292,96.484,2.170,10131.71,7.150,327.873

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent
0,Albania,-8.677,25.905,32.619,13394.46,108.613,-6.713,22.790,14.074,2.878,11.675,-27.509,-19.517,203.320,75.927,-3.482,15.161,EU
1,Algeria,-12.677,30.128,36.868,10747.35,211.180,-6.740,42.597,29.921,43.851,14.652,-4.154,-18.914,261.583,51.324,-4.900,147.600,AF
2,Argentina,0.852,33.466,42.092,19685.74,619.207,-8.626,17.913,18.765,45.388,11.550,-13.124,-10.722,4400.780,102.790,-9.895,389.064,SA
3,Armenia,-3.787,25.247,30.649,12631.53,218.396,-5.403,18.532,14.746,2.962,18.100,-35.571,-30.991,162.702,63.476,-7.395,12.641,AS
4,Australia,2.595,36.090,44.674,49088.42,116.175,-8.585,22.271,24.870,25.684,6.492,-9.822,-13.014,100.348,57.828,-2.179,1357.320,OC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-2.502,36.160,48.921,42975.53,108.736,-12.761,16.693,14.192,67.081,4.525,-12.961,-15.769,105.091,102.608,-9.270,2758.870,EU
87,United States,-2.949,30.804,45.296,59803.38,258.838,-14.492,21.152,19.158,331.234,8.092,-13.561,-8.933,113.647,134.238,-3.405,20893.750,NA
88,Uruguay,-0.839,28.124,32.793,21200.62,216.725,-4.668,17.423,16.585,3.531,10.350,-19.065,-12.710,135.485,68.143,-6.115,53.561,SA
89,Uzbekistan,-5.021,26.356,28.873,7415.02,313.051,-2.517,38.674,33.652,33.905,10.531,-20.029,-12.844,100.000,37.601,1.886,59.893,AS
90,Vietnam,4.391,18.535,22.444,10331.25,282.118,-3.909,32.110,36.485,97.406,3.300,3.569,2.655,159.726,41.668,2.944,342.941,AS

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class
0,Albania,-8.677,25.905,32.619,13394.46,108.613,-6.713,22.790,14.074,2.878,11.675,-27.509,-19.517,203.320,75.927,-3.482,15.161,EU,S2
1,Algeria,-12.677,30.128,36.868,10747.35,211.180,-6.740,42.597,29.921,43.851,14.652,-4.154,-18.914,261.583,51.324,-4.900,147.600,AF,S2
2,Argentina,0.852,33.466,42.092,19685.74,619.207,-8.626,17.913,18.765,45.388,11.550,-13.124,-10.722,4400.780,102.790,-9.895,389.064,SA,S3
3,Armenia,-3.787,25.247,30.649,12631.53,218.396,-5.403,18.532,14.746,2.962,18.100,-35.571,-30.991,162.702,63.476,-7.395,12.641,AS,S2
4,Australia,2.595,36.090,44.674,49088.42,116.175,-8.585,22.271,24.870,25.684,6.492,-9.822,-13.014,100.348,57.828,-2.179,1357.320,OC,S3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-2.502,36.160,48.921,42975.53,108.736,-12.761,16.693,14.192,67.081,4.525,-12.961,-15.769,105.091,102.608,-9.270,2758.870,EU,S4
87,United States,-2.949,30.804,45.296,59803.38,258.838,-14.492,21.152,19.158,331.234,8.092,-13.561,-8.933,113.647,134.238,-3.405,20893.750,NA,S3
88,Uruguay,-0.839,28.124,32.793,21200.62,216.725,-4.668,17.423,16.585,3.531,10.350,-19.065,-12.710,135.485,68.143,-6.115,53.561,SA,S2
89,Uzbekistan,-5.021,26.356,28.873,7415.02,313.051,-2.517,38.674,33.652,33.905,10.531,-20.029,-12.844,100.000,37.601,1.886,59.893,AS,S1
90,Vietnam,4.391,18.535,22.444,10331.25,282.118,-3.909,32.110,36.485,97.406,3.300,3.569,2.655,159.726,41.668,2.944,342.941,AS,S1

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class,debt_class
0,Albania,-8.677,25.905,32.619,13394.46,108.613,-6.713,22.790,14.074,2.878,11.675,-27.509,-19.517,203.320,75.927,-3.482,15.161,EU,S2,Very High
1,Algeria,-12.677,30.128,36.868,10747.35,211.180,-6.740,42.597,29.921,43.851,14.652,-4.154,-18.914,261.583,51.324,-4.900,147.600,AF,S2,40%-60%
2,Argentina,0.852,33.466,42.092,19685.74,619.207,-8.626,17.913,18.765,45.388,11.550,-13.124,-10.722,4400.780,102.790,-9.895,389.064,SA,S3,Very High
3,Armenia,-3.787,25.247,30.649,12631.53,218.396,-5.403,18.532,14.746,2.962,18.100,-35.571,-30.991,162.702,63.476,-7.395,12.641,AS,S2,Very High
4,Australia,2.595,36.090,44.674,49088.42,116.175,-8.585,22.271,24.870,25.684,6.492,-9.822,-13.014,100.348,57.828,-2.179,1357.320,OC,S3,40%-60%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-2.502,36.160,48.921,42975.53,108.736,-12.761,16.693,14.192,67.081,4.525,-12.961,-15.769,105.091,102.608,-9.270,2758.870,EU,S4,Very High
87,United States,-2.949,30.804,45.296,59803.38,258.838,-14.492,21.152,19.158,331.234,8.092,-13.561,-8.933,113.647,134.238,-3.405,20893.750,NA,S3,Very High
88,Uruguay,-0.839,28.124,32.793,21200.62,216.725,-4.668,17.423,16.585,3.531,10.350,-19.065,-12.710,135.485,68.143,-6.115,53.561,SA,S2,Very High
89,Uzbekistan,-5.021,26.356,28.873,7415.02,313.051,-2.517,38.674,33.652,33.905,10.531,-20.029,-12.844,100.000,37.601,1.886,59.893,AS,S1,20%-40%
90,Vietnam,4.391,18.535,22.444,10331.25,282.118,-3.909,32.110,36.485,97.406,3.300,3.569,2.655,159.726,41.668,2.944,342.941,AS,S1,40%-60%

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,...,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class,debt_class,invest/gdp_class
0,Albania,-8.677,25.905,32.619,13394.46,108.613,-6.713,22.790,14.074,2.878,...,-27.509,-19.517,203.320,75.927,-3.482,15.161,EU,S2,Very High,20%-30%
1,Algeria,-12.677,30.128,36.868,10747.35,211.180,-6.740,42.597,29.921,43.851,...,-4.154,-18.914,261.583,51.324,-4.900,147.600,AF,S2,40%-60%,>40
2,Argentina,0.852,33.466,42.092,19685.74,619.207,-8.626,17.913,18.765,45.388,...,-13.124,-10.722,4400.780,102.790,-9.895,389.064,SA,S3,Very High,0%-20%
3,Armenia,-3.787,25.247,30.649,12631.53,218.396,-5.403,18.532,14.746,2.962,...,-35.571,-30.991,162.702,63.476,-7.395,12.641,AS,S2,Very High,0%-20%
4,Australia,2.595,36.090,44.674,49088.42,116.175,-8.585,22.271,24.870,25.684,...,-9.822,-13.014,100.348,57.828,-2.179,1357.320,OC,S3,40%-60%,20%-30%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-2.502,36.160,48.921,42975.53,108.736,-12.761,16.693,14.192,67.081,...,-12.961,-15.769,105.091,102.608,-9.270,2758.870,EU,S4,Very High,0%-20%
87,United States,-2.949,30.804,45.296,59803.38,258.838,-14.492,21.152,19.158,331.234,...,-13.561,-8.933,113.647,134.238,-3.405,20893.750,NA,S3,Very High,20%-30%
88,Uruguay,-0.839,28.124,32.793,21200.62,216.725,-4.668,17.423,16.585,3.531,...,-19.065,-12.710,135.485,68.143,-6.115,53.561,SA,S2,Very High,0%-20%
89,Uzbekistan,-5.021,26.356,28.873,7415.02,313.051,-2.517,38.674,33.652,33.905,...,-20.029,-12.844,100.000,37.601,1.886,59.893,AS,S1,20%-40%,30%-40%
90,Vietnam,4.391,18.535,22.444,10331.25,282.118,-3.909,32.110,36.485,97.406,...,3.569,2.655,159.726,41.668,2.944,342.941,AS,S1,40%-60%,30%-40%

,country,continent,spend_class,debt_class,invest/gdp_class,acc_bal,gdp_defl,inflation_ind,gov_rev,gov_expend,...,tot_invest,gross_savings,export_g_s,import_g_s,gross_debt,pop,unemployment,gdp_percap_cons,gdp_cons,gdp_curr
0,Albania,EU,S2,Very High,20%-30%,-8.677,203.320,108.613,25.905,32.619,...,22.790,14.074,-27.509,-19.517,75.927,2.878,11.675,13394.46,-3.482,15.161
1,Algeria,AF,S2,40%-60%,>40,-12.677,261.583,211.180,30.128,36.868,...,42.597,29.921,-4.154,-18.914,51.324,43.851,14.652,10747.35,-4.900,147.600
2,Argentina,SA,S3,Very High,0%-20%,0.852,4400.780,619.207,33.466,42.092,...,17.913,18.765,-13.124,-10.722,102.790,45.388,11.550,19685.74,-9.895,389.064
3,Armenia,AS,S2,Very High,0%-20%,-3.787,162.702,218.396,25.247,30.649,...,18.532,14.746,-35.571,-30.991,63.476,2.962,18.100,12631.53,-7.395,12.641
4,Australia,OC,S3,40%-60%,20%-30%,2.595,100.348,116.175,36.090,44.674,...,22.271,24.870,-9.822,-13.014,57.828,25.684,6.492,49088.42,-2.179,1357.320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,EU,S4,Very High,0%-20%,-2.502,105.091,108.736,36.160,48.921,...,16.693,14.192,-12.961,-15.769,102.608,67.081,4.525,42975.53,-9.270,2758.870
87,United States,NA,S3,Very High,20%-30%,-2.949,113.647,258.838,30.804,45.296,...,21.152,19.158,-13.561,-8.933,134.238,331.234,8.092,59803.38,-3.405,20893.750
88,Uruguay,SA,S2,Very High,0%-20%,-0.839,135.485,216.725,28.124,32.793,...,17.423,16.585,-19.065,-12.710,68.143,3.531,10.350,21200.62,-6.115,53.561
89,Uzbekistan,AS,S1,20%-40%,30%-40%,-5.021,100.000,313.051,26.356,28.873,...,38.674,33.652,-20.029,-12.844,37.601,33.905,10.531,7415.02,1.886,59.893
90,Vietnam,AS,S1,40%-60%,30%-40%,4.391,159.726,282.118,18.535,22.444,...,32.110,36.485,3.569,2.655,41.668,97.406,3.300,10331.25,2.944,342.941

In [13]:
dd20

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,...,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class,debt_class,invest/gdp_class
0,Albania,-8.677,25.905,32.619,13394.46,108.613,-6.713,22.790,14.074,2.878,...,-27.509,-19.517,203.320,75.927,-3.482,15.161,EU,S2,Very High,20%-30%
1,Algeria,-12.677,30.128,36.868,10747.35,211.180,-6.740,42.597,29.921,43.851,...,-4.154,-18.914,261.583,51.324,-4.900,147.600,AF,S2,40%-60%,>40
2,Argentina,0.852,33.466,42.092,19685.74,619.207,-8.626,17.913,18.765,45.388,...,-13.124,-10.722,4400.780,102.790,-9.895,389.064,SA,S3,Very High,0%-20%
3,Armenia,-3.787,25.247,30.649,12631.53,218.396,-5.403,18.532,14.746,2.962,...,-35.571,-30.991,162.702,63.476,-7.395,12.641,AS,S2,Very High,0%-20%
4,Australia,2.595,36.090,44.674,49088.42,116.175,-8.585,22.271,24.870,25.684,...,-9.822,-13.014,100.348,57.828,-2.179,1357.320,OC,S3,40%-60%,20%-30%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-2.502,36.160,48.921,42975.53,108.736,-12.761,16.693,14.192,67.081,...,-12.961,-15.769,105.091,102.608,-9.270,2758.870,EU,S4,Very High,0%-20%
87,United States,-2.949,30.804,45.296,59803.38,258.838,-14.492,21.152,19.158,331.234,...,-13.561,-8.933,113.647,134.238,-3.405,20893.750,NA,S3,Very High,20%-30%
88,Uruguay,-0.839,28.124,32.793,21200.62,216.725,-4.668,17.423,16.585,3.531,...,-19.065,-12.710,135.485,68.143,-6.115,53.561,SA,S2,Very High,0%-20%
89,Uzbekistan,-5.021,26.356,28.873,7415.02,313.051,-2.517,38.674,33.652,33.905,...,-20.029,-12.844,100.000,37.601,1.886,59.893,AS,S1,20%-40%,30%-40%
90,Vietnam,4.391,18.535,22.444,10331.25,282.118,-3.909,32.110,36.485,97.406,...,3.569,2.655,159.726,41.668,2.944,342.941,AS,S1,40%-60%,30%-40%

In [ ]:
# d20['country'] = d20['country'].replace(['Hong Kong SAR',"Korea",'Kosovo','Taiwan Province of China','The Bahamas'], ['Hong Kong','Korea, Republic of','Montenegro','Taiwan, Province of China','Bahamas'])
# display(d20.head(40))
# d20['code'] = d20['country'].apply(pc.country_name_to_country_alpha2)
# display(d20.head(40))
# d20['continent'] = d20['code'].apply(pc.country_alpha2_to_continent_code)
# display(d20.head(40))
# d20.drop('code', axis=1, inplace=True)
# display(d20.head(40))
#     #rename Kosovo back
# d20['country'].replace('Montenegro', 'Kosovo')
# display(d20.head(40))

Saving to csv

In [45]:
dd15.to_csv('final_15.csv', index=False)
dd16.to_csv('final_16.csv', index=False)
dd17.to_csv('final_17.csv', index=False)
dd18.to_csv('final_18.csv', index=False)
dd19.to_csv('final_19.csv', index=False)
dd20.to_csv('final_20.csv', index=False)

In [44]:
gdp_15= pd.read_csv("final_15.csv", sep=',')
gdp_15

,country,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,...,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr,continent,spend_class,debt_class,invest/gdp_class
0,Albania,-8.609,26.440,30.758,12173.62,100.000,-4.318,26.237,15.804,2.881,...,5.272,0.076,194.969,73.716,2.219,11.389,EU,S2,Very High,20%-30%
1,Algeria,-16.442,30.544,45.811,11616.72,172.653,-15.267,50.781,34.326,39.963,...,5.733,-6.048,237.033,8.733,3.700,165.979,AF,S4,5%-20%,>40
2,Argentina,-2.743,35.366,41.366,23933.89,168.000,-6.001,17.071,14.328,43.132,...,-1.633,2.644,825.311,52.563,2.731,642.464,SA,S3,40%-60%,0%-20%
3,Armenia,-2.685,21.494,26.331,11074.41,208.046,-4.837,21.204,18.519,2.990,...,9.679,-9.819,149.985,44.133,3.254,10.553,AS,S2,40%-60%,20%-30%
4,Australia,-4.637,34.599,37.387,48757.65,107.650,-2.788,25.910,21.652,23.985,...,6.319,2.259,90.165,37.751,2.310,1233.140,OC,S3,20%-40%,20%-30%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,United Kingdom,-5.165,35.486,39.993,45208.37,100.000,-4.507,17.646,12.481,65.110,...,3.765,4.994,92.626,86.022,2.623,2957.230,EU,S3,Very High,0%-20%
87,United States,-2.246,31.673,35.205,58385.72,237.002,-3.532,21.201,20.156,320.926,...,0.271,5.187,104.691,105.142,2.707,18206.030,NaN,S3,Very High,20%-30%
88,Uruguay,-0.254,26.607,28.472,22069.82,146.058,-1.865,19.469,19.215,3.467,...,-7.755,-8.122,93.157,58.152,0.371,57.874,SA,S2,40%-60%,0%-20%
89,Uzbekistan,1.046,24.325,24.567,6458.15,166.288,-0.242,24.698,25.744,31.023,...,2.120,11.322,46.125,6.724,7.219,85.662,AS,S1,5%-20%,20%-30%
90,Vietnam,-0.861,19.190,24.174,8133.27,241.605,-4.983,31.825,30.944,91.713,...,14.065,18.363,140.427,46.116,6.987,236.795,AS,S1,40%-60%,30%-40%

Saving to SQL DB

In [23]:
password = getpass()

Â·Â·Â·Â·Â·Â·Â·Â·

In [47]:
password = getpass()

database_connection = sqlalchemy.create_engine('mysql+pymysql://root:'+password+'@127.0.0.1:3306/gdp')
                                             
dd15.to_sql(con=database_connection, name='gdp_15', if_exists='replace')
dd16.to_sql(con=database_connection, name='gdp_16', if_exists='replace')
dd17.to_sql(con=database_connection, name='gdp_17', if_exists='replace')
dd18.to_sql(con=database_connection, name='gdp_18', if_exists='replace')
dd19.to_sql(con=database_connection, name='gdp_19', if_exists='replace')
dd20.to_sql(con=database_connection, name='gdp_20', if_exists='replace')

In [15]:
!git add .

In [16]:
!git commit -m'start'

[main a388d93] start
 15 files changed, 13324 insertions(+), 2114 deletions(-)
 create mode 100644 d_15_g.csv
 create mode 100644 d_16_g.csv
 create mode 100644 d_17_g.csv
 create mode 100644 d_18_g.csv
 create mode 100644 d_19_g.csv
 delete mode 100644 d_20.csv
 create mode 100644 d_20_g.csv
 create mode 100644 final_15.csv
 create mode 100644 final_16.csv
 create mode 100644 final_17.csv
 create mode 100644 final_18.csv
 create mode 100644 final_19.csv
 create mode 100644 final_20.csv

In [17]:
!git push

Enumerating objects: 21, done.
Counting objects: 100% (20/20), done.
Delta compression using up to 4 threads
Compressing objects: 100% (16/16), done.
Writing objects: 100% (17/17), 82.43 KiB | 1.96 MiB/s, done.
Total 17 (delta 6), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (6/6), completed with 1 local object.
To https://github.com/chrislacarte/Country-GDP-and-Debt-predictor-ML-
   8c44dcc..a388d93  main -> main