In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pycountry
import csv
import pycountry_convert as pc

In [2]:
data_0 = pd.read_csv("WEO_Data.csv", sep=',')
data_0

,Country,Subject Descriptor,2015,2016,2017,2018,2019,2020,Estimates Start After
0,Albania,"Gross domestic product, constant prices",2.219,3.315,3.802,4.019,2.088,-3.482,2020
1,Albania,"Gross domestic product, current prices",11.389,11.862,13.053,15.157,15.399,15.161,2020
2,Albania,"Gross domestic product, deflator",194.969,193.736,196.547,199.442,201.949,203.32,2020
3,Albania,"Gross domestic product per capita, constant pr...","12,173.62","12,597.30","13,039.70","13,570.55","13,862.63","13,394.46",2020
4,Albania,Total investment,26.237,25.47,24.672,24.118,23.032,22.79,2020
...,...,...,...,...,...,...,...,...,...
1451,Vietnam,General government revenue,19.19,19.067,19.565,19.547,19.648,18.535,2020
1452,Vietnam,General government total expenditure,24.174,22.231,21.529,20.573,20.05,22.444,2020
1453,Vietnam,General government net lending/borrowing,-4.983,-3.164,-1.964,-1.026,-0.402,-3.909,2020
1454,Vietnam,General government gross debt,46.116,47.548,46.32,43.712,41.292,41.668,2020
1455,Vietnam,Current account balance,-0.861,0.248,-0.596,1.903,3.711,4.391,2020

# INFO TABLE

In [3]:
info= pd.read_csv("WEO_info.csv", sep=',')
info

,"Gross domestic product, constant prices",Percent change,Unnamed: 2,"See notes for: Gross domestic product, constant prices (National currency)."
0,"Gross domestic product, current prices",U.S. dollars,Billions,"See notes for: Gross domestic product, curren..."
1,"Gross domestic product, deflator",Index,NaN,"See notes for: Gross domestic product, consta..."
2,"Gross domestic product per capita, constant pr...",Purchasing power parity; 2017 international do...,Units,"See notes for: Gross domestic product, consta..."
3,Total investment,Percent of GDP,NaN,Source: IMF Staff Estimates. Official national...
4,Gross national savings,Percent of GDP,NaN,Source: IMF Staff Estimates. Official national...
5,"Inflation, average consumer prices",Index,NaN,Source: National Statistics Office Latest actu...
6,Volume of imports of goods and services,Percent change,NaN,Source: Central Bank Latest actual data: 2020 ...
7,Volume of exports of goods and services,Percent change,NaN,Source: Central Bank Latest actual data: 2020 ...
8,Unemployment rate,Percent of total labor force,NaN,Source: National Statistics Office Latest actu...
9,Population,Persons,Millions,Source: National Statistics Office. INSTAT Lat...
10,General government revenue,Percent of GDP,NaN,See notes for: General government revenue (Na...
11,General government total expenditure,Percent of GDP,NaN,See notes for: General government total expen...
12,General government net lending/borrowing,Percent of GDP,NaN,See notes for: General government net lending...
13,General government gross debt,Percent of GDP,NaN,See notes for: General government gross debt ...
14,Current account balance,Percent of GDP,NaN,"See notes for: Gross domestic product, curren..."

In [4]:
cols = []
for i in range(len(data_0.columns)):
    cols.append(data_0.columns[i].lower().replace(' ', '_'))
data_0.columns = cols
data_0.head(15)

,country,subject_descriptor,2015,2016,2017,2018,2019,2020,estimates_start_after
0,Albania,"Gross domestic product, constant prices",2.219,3.315,3.802,4.019,2.088,-3.482,2020
1,Albania,"Gross domestic product, current prices",11.389,11.862,13.053,15.157,15.399,15.161,2020
2,Albania,"Gross domestic product, deflator",194.969,193.736,196.547,199.442,201.949,203.32,2020
3,Albania,"Gross domestic product per capita, constant pr...","12,173.62","12,597.30","13,039.70","13,570.55","13,862.63","13,394.46",2020
4,Albania,Total investment,26.237,25.47,24.672,24.118,23.032,22.79,2020
5,Albania,Gross national savings,15.804,16.796,17.085,17.109,14.742,14.074,2020
6,Albania,"Inflation, average consumer prices",100,101.287,103.297,105.393,106.88,108.613,2020
7,Albania,Volume of imports of goods and services,0.076,8.3,5.993,5.765,4.716,-19.517,2020
8,Albania,Volume of exports of goods and services,5.272,10.396,10.1,3.469,1.695,-27.509,2020
9,Albania,Unemployment rate,17.1,15.2,13.7,12.3,11.47,11.675,2020
10,Albania,Population,2.881,2.876,2.884,2.883,2.881,2.878,2020
11,Albania,General government revenue,26.44,27.642,27.756,27.485,27.209,25.905,2020
12,Albania,General government total expenditure,30.758,29.139,29.372,28.802,29.153,32.619,2020
13,Albania,General government net lending/borrowing,-4.318,-1.498,-1.616,-1.317,-1.944,-6.713,2020
14,Albania,General government gross debt,73.716,73.324,71.895,69.466,67.285,75.927,2020

In [5]:
data_15 = data_0[['country', 'subject_descriptor', '2015']]
data_16 = data_0[['country', 'subject_descriptor', '2016']]
data_17 = data_0[['country', 'subject_descriptor', '2017']]
data_18 = data_0[['country', 'subject_descriptor', '2018']]
data_19 = data_0[['country', 'subject_descriptor', '2019']]
data_20 = data_0[['country', 'subject_descriptor', '2020']]
data_15.head(16)

    country                                 subject_descriptor       2015
0   Albania            Gross domestic product, constant prices      2.219
1   Albania             Gross domestic product, current prices     11.389
2   Albania                   Gross domestic product, deflator    194.969
3   Albania  Gross domestic product per capita, constant pr...  12,173.62
4   Albania                                   Total investment     26.237
5   Albania                             Gross national savings     15.804
6   Albania                 Inflation, average consumer prices        100
7   Albania            Volume of imports of goods and services      0.076
8   Albania            Volume of exports of goods and services      5.272
9   Albania                                  Unemployment rate       17.1
10  Albania                                         Population      2.881
11  Albania                         General government revenue      26.44
12  Albania               General government total expenditure     30.758
13  Albania           General government net lending/borrowing     -4.318
14  Albania                      General government gross debt     73.716
15  Albania                            Current account balance     -8.609

# FROM HERE ALL TRANSFORMATIONS ARE  INCLUDED IN CLEANING FUNCTIONS AT THE END

In [9]:
def pivot_and_column_names(df):
        df= df.pivot(index='country', columns=df[['subject_descriptor']])
        #rename columns:
        df.columns = ['acc_bal','gross_debt','gov_net_len/borr','gov_rev','gov_expend','gdp_percap_cons','gdp_cons',
                      'gdp_curr', 'gdp_defl', 'gross_savings','inflation_ind','pop','tot_invest', 'unemployment', 
                      'export_g_s', 'import_g_s']
        #arrange order:
        df = df[['acc_bal','gov_rev','gov_expend','gdp_percap_cons','inflation_ind','gov_net_len/borr','tot_invest',
                    'gross_savings','pop', 'unemployment', 
                    'export_g_s', 'import_g_s','gdp_defl','gross_debt','gdp_cons','gdp_curr']]
        return df
pivot_and_column_names(data_20)

,acc_bal,gob rev,gov_expend,gdp_percap_cons,inflation_ind,gob_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr
country,,,,,,,,,,,,,,,,
Albania,-8.677,25.905,32.619,"13,394.46",108.613,-6.713,22.79,14.074,2.878,11.675,-27.509,-19.517,203.32,75.927,-3.482,15.161
Algeria,-12.677,30.128,36.868,"10,747.35",211.18,-6.74,42.597,29.921,43.851,14.652,-4.154,-18.914,261.583,51.324,-4.9,147.6
Argentina,0.852,33.466,42.092,"19,685.74",619.207,-8.626,17.913,18.765,45.388,11.55,-13.124,-10.722,"4,400.78",102.79,-9.895,389.064
Armenia,-3.787,25.247,30.649,"12,631.53",218.396,-5.403,18.532,14.746,2.962,18.1,-35.571,-30.991,162.702,63.476,-7.395,12.641
Australia,2.595,36.09,44.674,"49,088.42",116.175,-8.585,22.271,24.87,25.684,6.492,-9.822,-13.014,100.348,57.828,-2.179,"1,357.32"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
United Kingdom,-2.502,36.16,48.921,"42,975.53",108.736,-12.761,16.693,14.192,67.081,4.525,-12.961,-15.769,105.091,102.608,-9.27,"2,758.87"
United States,-2.949,30.804,45.296,"59,803.38",258.838,-14.492,21.152,19.158,331.234,8.092,-13.561,-8.933,113.647,134.238,-3.405,"20,893.75"
Uruguay,-0.839,28.124,32.793,"21,200.62",216.725,-4.668,17.423,16.585,3.531,10.35,-19.065,-12.71,135.485,68.143,-6.115,53.561
Uzbekistan,-5.021,26.356,28.873,"7,415.02",313.051,-2.517,38.674,33.652,33.905,10.531,-20.029,-12.844,100,37.601,1.886,59.893
Vietnam,4.391,18.535,22.444,"10,331.25",282.118,-3.909,32.11,36.485,97.406,3.3,3.569,2.655,159.726,41.668,2.944,342.941

In [10]:
d_15 = column_names(data_15)
d_16 = column_names(data_16)
d_17 = column_names(data_17)
d_18 = column_names(data_18)
d_19 = column_names(data_19)
d_20 = column_names(data_20)
d_15

NameError: name 'column_names' is not defined

In [ ]:
#I see the column 'gdp_percap_cons' has commas to separate the 1000s 
#as per error: 'could not convert string to float: '12,173.62''

# https://www.adamsmith.haus/python/answers/how-to-remove-a-comma-from-a-string-in-python

def clean_comma(df):
    for i in df.columns:
        df[i] = df[i].str.replace(',', '')
    return df 
clean_comma(d_15)
clean_comma(d_16)
clean_comma(d_17)
clean_comma(d_18)
clean_comma(d_19)
clean_comma(d_20)

#I will include it in the cleaning function

In [ ]:
#transform dtypes to numerics 
def to_num(df):
    df = df.astype(np.number)
    print(df.dtypes)

to_num(d_15)
to_num(d_16)
to_num(d_17)
to_num(d_18)
to_num(d_19)
to_num(d_20)
display(d_20)

In [ ]:
d_15.to_csv('d_15.csv', index=True)
d_16.to_csv('d_16.csv', index=True)
d_17.to_csv('d_17.csv', index=True)
d_18.to_csv('d_18.csv', index=True)
d_19.to_csv('d_19.csv', index=True)
d_20.to_csv('d_20.csv', index=True)

In [ ]:
d15 = pd.read_csv("d_15.csv")
d16 = pd.read_csv("d_16.csv")
d17 = pd.read_csv("d_17.csv")
d18 = pd.read_csv("d_18.csv")
d19 = pd.read_csv("d_19.csv")
d20 = pd.read_csv("d_20.csv")
d15

In [ ]:
d15.isnull().sum()

In [ ]:
d15.dtypes

Add 2 categorical columns by region and by economy size

Region / Continent :

I found this library "pycountry" :

Which through the country code, gives the continent. 
import pycountry_convert as pc

country_code = pc.country_name_to_country_alpha2("China", cn_name_format="default")
print(country_code)
continent_name = pc.country_alpha2_to_continent_code(country_code)
print(continent_name)
I am going to create a colulmn called "region"

In [ ]:
#clean and convert not ISO recognised country names 
#list of correct contry names (ISO) found here: 
#https://stackoverflow.com/questions/16253060/how-to-convert-country-names-to-iso-3166-1-alpha-2-values-using-python
# 'Kosovo' is not a recognsed country by ISO 3166 so I am going to name it Serbia (keeps the index order) just to get the country code

def replace_wrong_names(df):
    df[['country']] = df[['country']].replace(['Hong Kong SAR',"Korea",'Kosovo', 'Taiwan Province of China', 'The Bahamas' ], ['Hong Kong', 'Korea, Republic of', 'Serbia','Taiwan, Province of China',  'Bahamas'])

replace_wrong_names(d15)
replace_wrong_names(d16)
replace_wrong_names(d17)
replace_wrong_names(d18)
replace_wrong_names(d19)
replace_wrong_names(d20)

In [ ]:
def code_co(df):
    df['code'] = df['country'].apply(pc.country_name_to_country_alpha2)
   

code_co(d15)
code_co(d16)
code_co(d17)
code_co(d18)
code_co(d19)
code_co(d20)




# d15['code'] = d15['country'].apply(pc.country_name_to_country_alpha2)
# d15['code']

In [ ]:
def create_cont(df):
    df['continent'] = df['code'].apply(pc.country_alpha2_to_continent_code)
    df.drop('code', axis=1, inplace=True)
    #rename Kosovo back
    df['country'][43]= 'Kosovo'


create_cont(d15)
create_cont(d16)
create_cont(d17)
create_cont(d18)
create_cont(d19)
create_cont(d20)

# d15['continent'] = d15['code'].apply(pc.country_alpha2_to_continent_code)
# d15['continent'] 
# continents = {
#     'NA': 'North America',
#     'SA': 'South America', 
#     'AS': 'Asia',
#     'OC': 'Australia',
#     'AF': 'Africa',
#     'EU': 'Europe'
# }

In [ ]:
d15

Economy size: 



% GDP growth Vs LY 
Unemployment
Population

In [ ]:
#add a new column with a classification (Total expenditure)

In [ ]:
# % of GDP
def spend_class(df):
    df['spend_class'] = df["gov_expend"].copy()
    labels = ["S1", "S2", "S3","S4"]
    df['spend_class'] = pd.qcut(df["gov_expend"],4, labels = labels)

    
create_spend_class(d20)

In [ ]:
d15['gross_debt'].describe()

In [ ]:
def gross_debt_class(df):
    labels = ["0%-5%", "5%-20%", "20%-40%", "40%-60%", "Very High"]
    df['debt_class'] = pd.cut(df['gross_debt'],[0,5,20,40,60,228.397000], labels = labels)
    
gross_debt_class(d20)

In [ ]:
d15['tot_invest'].describe()

In [ ]:
def invest_class(df):
    labels = ["0%-20%", "20%-30%", "30%-40%", ">40"]
    df['invest/gdp_class'] = pd.cut(df['tot_invest'],[12,20,30,40,51], labels = labels)
   
invest_class(d20)

In [ ]:
def order_columns(df):
    df= df[['country','continent','acc_bal','gdp_defl','inflation_ind','gob rev','gov_expend','gob_net_len/borr','tot_invest',
                'gross_savings', 'export_g_s', 'import_g_s','gross_debt','pop', 'unemployment','gdp_percap_cons','gdp_cons','gdp_curr']]

In [18]:
def data_grooming(df):
    df = df.pivot(index='country', columns=df[['subject_descriptor']])
    #rename columns:
    df.columns = ['acc_bal','gross_debt','gov_net_len/borr','gov_rev','gov_expend','gdp_percap_cons','gdp_cons',
                    'gdp_curr', 'gdp_defl', 'gross_savings','inflation_ind','pop','tot_invest', 'unemployment', 
                    'export_g_s', 'import_g_s']
    #arrange order:
    df = df[['acc_bal','gov_rev','gov_expend','gdp_percap_cons','inflation_ind','gov_net_len/borr','tot_invest',
                    'gross_savings','pop', 'unemployment', 
                    'export_g_s', 'import_g_s','gdp_defl','gross_debt','gdp_cons','gdp_curr']]
    #clean commas in 1000s values:
    for i in df.columns:
        df[i] = df[i].str.replace(',', '')
    #transform dtypes to numerics 
    df = df.astype(np.number)
    return df
    
    
def data_cleaning(df):
    
    df[['country']] = df[['country']].replace(['Hong Kong SAR',"Korea",'Kosovo', 'Taiwan Province of China', 'The Bahamas' ], ['Hong Kong', 'Korea, Republic of', 'Serbia','Taiwan, Province of China',  'Bahamas'])
    df['code'] = df['country'].apply(pc.country_name_to_country_alpha2)
    df['continent'] = df['code'].apply(pc.country_alpha2_to_continent_code)
    df.drop('code', axis=1, inplace=True)
    #rename Kosovo back
    df['country'][43]= 'Kosovo'

    #Spend_class
    df['spend_class'] = df["gov_expend"].copy()
    labels = ["S1", "S2", "S3","S4"]
    df['spend_class'] = pd.qcut(df["gov_expend"],4, labels = labels)
    
    #gross_debt_class
    df['debt_class'] = df["gross_debt"].copy()
    labels = ["0%-5%", "5%-20%", "20%-40%", "40%-60%", "Very High"]
    df['debt_class'] = pd.cut(df['gross_debt'],[0,5,20,40,60,228.397000], labels = labels)
    
    #invest_class(df):
    df['invest/gdp_class'] = df["tot_invest"].copy()
    labels = ["0%-20%", "20%-30%", "30%-40%", ">40"]
    df['invest/gdp_class'] = pd.cut(df['tot_invest'],[12,20,30,40,51], labels = labels)
   
    
    #reorder columns :
    df= df[['country','continent','spend_class','debt_class','invest/gdp_class','acc_bal','gdp_defl','inflation_ind','gob rev','gov_expend','gob_net_len/borr','tot_invest',
                'gross_savings', 'export_g_s', 'import_g_s','gross_debt','pop', 'unemployment','gdp_percap_cons','gdp_cons','gdp_curr']]

In [9]:
data_grooming(data_20)

,acc_bal,gov_rev,gov_expend,gdp_percap_cons,inflation_ind,gov_net_len/borr,tot_invest,gross_savings,pop,unemployment,export_g_s,import_g_s,gdp_defl,gross_debt,gdp_cons,gdp_curr
country,,,,,,,,,,,,,,,,
Albania,-8.677,25.905,32.619,13394.46,108.613,-6.713,22.790,14.074,2.878,11.675,-27.509,-19.517,203.320,75.927,-3.482,15.161
Algeria,-12.677,30.128,36.868,10747.35,211.180,-6.740,42.597,29.921,43.851,14.652,-4.154,-18.914,261.583,51.324,-4.900,147.600
Argentina,0.852,33.466,42.092,19685.74,619.207,-8.626,17.913,18.765,45.388,11.550,-13.124,-10.722,4400.780,102.790,-9.895,389.064
Armenia,-3.787,25.247,30.649,12631.53,218.396,-5.403,18.532,14.746,2.962,18.100,-35.571,-30.991,162.702,63.476,-7.395,12.641
Australia,2.595,36.090,44.674,49088.42,116.175,-8.585,22.271,24.870,25.684,6.492,-9.822,-13.014,100.348,57.828,-2.179,1357.320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
United Kingdom,-2.502,36.160,48.921,42975.53,108.736,-12.761,16.693,14.192,67.081,4.525,-12.961,-15.769,105.091,102.608,-9.270,2758.870
United States,-2.949,30.804,45.296,59803.38,258.838,-14.492,21.152,19.158,331.234,8.092,-13.561,-8.933,113.647,134.238,-3.405,20893.750
Uruguay,-0.839,28.124,32.793,21200.62,216.725,-4.668,17.423,16.585,3.531,10.350,-19.065,-12.710,135.485,68.143,-6.115,53.561
Uzbekistan,-5.021,26.356,28.873,7415.02,313.051,-2.517,38.674,33.652,33.905,10.531,-20.029,-12.844,100.000,37.601,1.886,59.893
Vietnam,4.391,18.535,22.444,10331.25,282.118,-3.909,32.110,36.485,97.406,3.300,3.569,2.655,159.726,41.668,2.944,342.941

In [10]:
# d_15.to_csv('d_15.csv', index=True)
# d_16.to_csv('d_16.csv', index=True)
# d_17.to_csv('d_17.csv', index=True)
# d_18.to_csv('d_18.csv', index=True)
# d_19.to_csv('d_19.csv', index=True)
data_20.to_csv('d_20.csv', index=True)

In [11]:
# d15 = pd.read_csv("d_15.csv")
# d16 = pd.read_csv("d_16.csv")
# d17 = pd.read_csv("d_17.csv")
# d18 = pd.read_csv("d_18.csv")
# d19 = pd.read_csv("d_19.csv")
d20 = pd.read_csv("d_20.csv")

In [19]:
gdp_20 = data_cleaning(d20)
gdp_20

/var/folders/hq/x_513gjd2qsd86w2rwvd665m0000gn/T/ipykernel_71304/2185242573.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['country'][43]= 'Kosovo'

KeyError: 'gov_expend'

In [ ]:
!git add .

In [ ]:
!git commit -m'start'

In [ ]:
!git push

In [ ]:
for i in d15['region']:
    d15['region'][i] = country_to_continent(i)
    
d15['region']